export const builderEn={
  syntheticDemo:'Synthetic test data · 30 days, 10 EMA periods, TP/SL 1–2%. Parameters are checked automatically; submit starts only when you click.',collapse:'Collapse settings',resume:'Continue setup',animation:'Animation',motionoff:'Off',motionfast:'Fast',motionnormal:'Normal',motionslow:'Slow',reset:'Reset form', closeSettings:'Close settings', cancel:'Cancel', staleShort:'Check again after changes', groupMarket:'Market', groupSignal:'Signal', groupTrade:'Trade', groupRisk:'Risk', groupRanking:'Ranking', draftShort:'Draft until reload', chooseSources:'Select sources', unchecked:'Not checked yet', checked:'Configuration checked', reviewHelp:'Data coverage, cost and effective settings', configure:'Calculation console', checking:'Checking configuration…', preflight:'Check configuration', submit:'Submit backtest', submitting:'Submitting once…',
  loading:'Loading defaults and catalog…', unavailable:'Defaults or catalog are unavailable. Submission is blocked.', reloadInputs:'Reload catalog',
  label:'Job label (optional)', labelHelp:'History label only. Spaces are normalized and the server keeps the first 96 characters.',
  exchange:'Exchange', market:'Market type', symbol:'Symbol', timeframe:'Timeframe', start:'Start date', end:'End date',
  utcHelp:'UTC · Start inclusive, end exclusive.',
  indicators:'Ordered indicators', indicator:'Indicator', sources:'Price sources', windowStart:'Window start', windowStop:'Window stop', windowStep:'Window step', add:'Add indicator', remove:'Remove indicator', up:'Move up', down:'Move down',
  noWindow:'Unavailable: this API requires a window axis.', supportedWindow:'Materialized window values', sourceLess:'This indicator has no price-source axis.',
  risk:'Risk mode', tp:'Take profit', sl:'Stop loss', enabled:'Enabled', startPct:'Start (%)', stopPct:'Stop (%)', stepPct:'Step (%)', covered:'Covered levels (%)',
  execution:'Execution', direction:'Direction', cash:'Initial cash (quote)', fee:'Fee (%)', slippage:'Slippage (%)', sizing:'Position sizing', quote:'Quote amount', equity:'Equity (%)', minQuote:'Minimum quote', maxQuote:'Maximum quote',
  ranking:'Ranking', metric:'Primary metric', rankingDirection:'Ranking direction', topN:'Top N', policies:'Server policies', funding:'Funding', profitLock:'Profit lock', closeOnEnd:'Close on end', quality:'Minimum-trade policy',
  defaultsHelp:'These policies come from server defaults. Effective settings are shown after checking.',
  draftHelp:'Collapsing settings keeps the draft. Leaving Backtests or reloading discards it.', discard:'Discard unsent configuration? Leaving or reloading loses these edits.',
  storageWarning:'Tab storage is unavailable. Recovery is kept in memory only; leaving or reloading loses the request record.', storageChanged:'Tab storage failed while saving. The request has NOT been sent. Read the limitation and submit explicitly to continue with memory-only recovery.',
  review:'Preflight review', advisory:'Preflight is advisory. Submission checks data availability and admission again.', stale:'Configuration changed. Check it again before submitting.',
  invalid:'Correct the configuration', cost:'Server cost estimate', artifacts:'Selected artifact', asof:'As-of date', published:'Published · UTC', bounds:'Maximum end · UTC', generation:'Generation', sourceFreshness:'Catalog read · UTC',
  normalized:'Effective settings', fundingQuality:'Funding coverage', warnings:'Server warnings',
  unresolved:'Submission outcome is unresolved', recoveryHelp:'Do not submit this request again. Check job history. A missing history row does not prove failure. Safe replay is unavailable because the API cannot bind it to the original organization. No command is retried automatically.',
  recoveryTime:'Attempt time · UTC', recoveryKey:'Request key', recoveryJob:'Read known job', history:'Open job history', frozen:'Request and key are frozen.',
  rejected:'The server rejected submission. Your inputs are retained.', revise:'Correct rejected configuration', conflict:'The key conflicts with a different effective request. Keep this identity and check history. Changing only the label does not create a new computation.',
  tooLarge:'The recovery record is too large. Reduce the indicator configuration before submitting.',
  errors:{unsupported:'Choose a supported available value.',positiveInteger:'Enter a positive whole number.',positive:'Enter a finite value greater than zero.',nonnegative:'Enter a finite value of zero or more.',utc:'Choose a valid calendar date.',halfOpen:'End must be later than start.',boundsUnavailable:'Artifact date bounds are unavailable for this instrument.',dateBounds:'End exceeds the published artifact date bound.',catalogUnavailable:'The catalog is unavailable.',arity:'Use a nonempty indicator list within the server arity limit.',sources:'Select only the supported sources; source-based indicators need at least one.',grid:'Use positive integer window values covered by the catalog, with start ≤ stop.',cost:'The grid exceeds server resource limits.',riskTimeframe:'TP/SL requires the hit-times timeframe shown by the server.',riskEmpty:'Enable take profit, stop loss, or both.',riskGrid:'Use only covered TP/SL levels, with start ≤ stop.',percent:'Equity percentage must be at most 100.',fundingMetric:'This metric requires futures with funding included.',topN:'Top N exceeds the server limit.',validation:'The server rejected these parameters. Correct the fields below.',forbidden:'You do not have permission to submit this request.', 'not-found':'The requested resource is absent or not visible. This does not prove an earlier submission failed.', 'rate-limited':'Too many requests. Wait for the displayed delay; commands are never retried automatically.',unavailable:'Artifacts, admission or the queue are unavailable. Keep your configuration and check later.',transport:'The request did not complete. Keep your configuration.', 'invalid-response':'The response could not be read.',unauthenticated:'Your session has ended.',conflict:'The server reported an identity conflict.'}
};
export const builderRu:typeof builderEn={
  syntheticDemo:'Синтетические тестовые данные · 30 дней, 10 периодов EMA, TP/SL 1–2%. Проверка параметров автоматическая; запуск — только по нажатию.',collapse:'Свернуть настройку',resume:'Продолжить настройку',animation:'Анимация',motionoff:'Без анимации',motionfast:'Быстро',motionnormal:'Обычно',motionslow:'Медленно',reset:'Сбросить форму', closeSettings:'Закрыть настройку', cancel:'Отмена',staleShort:'Проверьте изменённые параметры',groupMarket:'Рынок',groupSignal:'Сигнал',groupTrade:'Сделка',groupRisk:'Риск',groupRanking:'Отбор',draftShort:'Черновик до перезагрузки',chooseSources:'Выберите источники',unchecked:'Проверка не выполнена',checked:'Параметры проверены',reviewHelp:'Покрытие данных, ресурсы и эффективные настройки',configure:'Пульт расчёта',checking:'Проверяем параметры…',preflight:'Проверить параметры',submit:'Отправить бэктест',submitting:'Отправляем один раз…',loading:'Загружаем настройки и каталог…',unavailable:'Настройки или каталог недоступны. Отправка заблокирована.',reloadInputs:'Обновить каталог',
  label:'Название задания (необязательно)',labelHelp:'Только подпись в истории. Сервер нормализует пробелы и сохраняет первые 96 символов.',exchange:'Биржа',market:'Тип рынка',symbol:'Символ',timeframe:'Таймфрейм',start:'Дата начала',end:'Дата окончания',utcHelp:'UTC · Начало включительно, конец не включительно.',
  indicators:'Порядок индикаторов',indicator:'Индикатор',sources:'Источники цены',windowStart:'Окно: начало',windowStop:'Окно: конец',windowStep:'Окно: шаг',add:'Добавить индикатор',remove:'Удалить индикатор',up:'Выше',down:'Ниже',noWindow:'Недоступен: API требует ось window.',supportedWindow:'Материализованные значения окна',sourceLess:'У этого индикатора нет оси источника цены.',
  risk:'Режим риска',tp:'Тейк-профит',sl:'Стоп-лосс',enabled:'Включён',startPct:'Начало (%)',stopPct:'Конец (%)',stepPct:'Шаг (%)',covered:'Доступные уровни (%)',execution:'Исполнение',direction:'Направление',cash:'Капитал (валюта котировки)',fee:'Комиссия (%)',slippage:'Проскальзывание (%)',sizing:'Размер позиции',quote:'Сумма в котируемой валюте',equity:'Доля капитала (%)',minQuote:'Минимальная сумма',maxQuote:'Максимальная сумма',ranking:'Ранжирование',metric:'Основная метрика',rankingDirection:'Порядок',topN:'Топ N',policies:'Политики сервера',funding:'Фандинг',profitLock:'Фиксация прибыли',closeOnEnd:'Закрывать в конце',quality:'Политика минимума сделок',defaultsHelp:'Политики получены из настроек сервера. Эффективные значения появятся после проверки.',draftHelp:'Сворачивание настройки сохраняет черновик. Уход из бэктестов или перезагрузка удалит его.',discard:'Сбросить неотправленные параметры? Переход или перезагрузка удалит изменения.',storageWarning:'Хранилище вкладки недоступно. Запись восстановления хранится только в памяти и будет потеряна при переходе или перезагрузке.',storageChanged:'Хранилище вкладки отказало при сохранении. Запрос НЕ отправлен. Прочитайте ограничение и явно отправьте снова для работы только с памятью.',review:'Результат проверки',advisory:'Проверка предварительная. При отправке сервер заново проверяет данные и доступные ресурсы.',stale:'Параметры изменены. Проверьте их перед отправкой.',invalid:'Исправьте параметры',cost:'Оценка ресурсов сервера',artifacts:'Выбранный артефакт',asof:'Дата данных',published:'Опубликован · UTC',bounds:'Максимальный конец · UTC',generation:'Поколение',sourceFreshness:'Каталог прочитан · UTC',normalized:'Эффективные настройки',fundingQuality:'Покрытие фандинга',warnings:'Предупреждения сервера',unresolved:'Результат отправки неизвестен',recoveryHelp:'Не отправляйте запрос повторно. Проверьте историю заданий: отсутствие строки не доказывает отказ. Безопасный повтор недоступен: API не связывает его с исходной организацией. Команды не повторяются автоматически.',recoveryTime:'Время попытки · UTC',recoveryKey:'Ключ запроса',recoveryJob:'Прочитать известное задание',history:'Открыть историю заданий',frozen:'Запрос и ключ зафиксированы.',rejected:'Сервер отклонил отправку. Параметры сохранены.',revise:'Исправить отклонённые параметры',conflict:'Ключ конфликтует с другим эффективным запросом. Сохраните идентичность и проверьте историю. Изменение названия не создаёт новое вычисление.',tooLarge:'Запись восстановления слишком велика. Уменьшите набор индикаторов перед отправкой.',
  errors:{unsupported:'Выберите поддерживаемое доступное значение.',positiveInteger:'Введите положительное целое число.',positive:'Введите конечное число больше нуля.',nonnegative:'Введите конечное неотрицательное число.',utc:'Выберите корректную календарную дату.',halfOpen:'Конец должен быть позже начала.',boundsUnavailable:'Границы дат артефакта недоступны для этого инструмента.',dateBounds:'Конец выходит за опубликованную границу артефакта.',catalogUnavailable:'Каталог недоступен.',arity:'Нужен непустой набор индикаторов в пределах лимита сервера.',sources:'Выберите поддерживаемые источники; ценовому индикатору нужен хотя бы один.',grid:'Нужны положительные целые значения окна из каталога, начало ≤ конец.',cost:'Сетка превышает ограничения ресурсов сервера.',riskTimeframe:'Для TP/SL нужен таймфрейм hit-times, указанный сервером.',riskEmpty:'Включите тейк-профит, стоп-лосс или оба.',riskGrid:'Используйте покрытые уровни TP/SL, начало ≤ конец.',percent:'Доля капитала не должна превышать 100%.',fundingMetric:'Метрике нужны фьючерсы с учётом фандинга.',topN:'Топ N превышает лимит сервера.',validation:'Сервер отклонил параметры. Исправьте указанные поля.',forbidden:'Нет разрешения на отправку этого запроса.','not-found':'Ресурс отсутствует или недоступен. Это не доказывает отказ предыдущей отправки.','rate-limited':'Слишком много запросов. Дождитесь указанного срока; команды не повторяются автоматически.',unavailable:'Артефакты, ресурсы или очередь недоступны. Сохраните параметры и проверьте позже.',transport:'Запрос не завершён. Параметры сохранены.','invalid-response':'Не удалось прочитать ответ.',unauthenticated:'Сессия завершена.',conflict:'Сервер сообщил о конфликте идентичности.'}
};
export const builderTermsEn:Record<string,string>={
  limit_scope:'Limited resource',limit:'Server limit',requested:'Requested',used:'In use',on:'Enabled',off:'Disabled',mode:'Mode',coverage_policy:'Coverage policy',enabled:'Enabled',safe_profit_percent:'Safe profit (%)',
  min_closed_trades:'Minimum closed trades',min_closed_trades_policy:'Minimum-trade policy',base_trades_per_year_at_1h:'Base trades/year at 1h',min_trades_per_year:'Minimum trades/year',max_trades_per_year:'Maximum trades/year',
  include_when_futures:'Include for futures',degraded_with_warning:'Warn on incomplete coverage',timeframe_sqrt_v1:'Automatic · timeframe and period',
  indicator_rows:'Indicator rows',candidate_combinations:'Candidate combinations',tp_sl_cells:'TP/SL cells',cost_class:'Cost class',scheduling_class:'Scheduling class',small:'Small',medium:'Medium',large:'Large',light:'Light',heavy:'Heavy',
  status:'Status',coverage_ratio:'Coverage (%)',rows_count:'Funding rows',expected_event_count:'Expected funding events',missing_event_count:'Missing funding events',warning_codes:'Coverage warnings',not_applicable:'Not applicable',ready:'Ready',degraded:'Incomplete',unavailable:'Unavailable',
  all_in:'All available capital',fixed_quote:'Fixed quote amount',fixed_equity_pct:'Fixed equity share',fixed_equity_pct_min_quote:'Equity share with minimum amount',fixed_equity_pct_max_quote:'Equity share with maximum amount',quote_amount:'Quote amount',equity_pct:'Equity (%)',min_quote:'Minimum quote',max_quote:'Maximum quote',
  long_only:'Long only',short:'Short',long_short_reversal:'Long/short reversal',none:'No TP/SL',tp_sl_grid:'TP/SL grid',asc:'Ascending',desc:'Descending',spot:'Spot',futures:'Futures',
  total_return_pct:'Total return (%)',total_return_pct_net_of_funding:'Return after funding (%)',max_drawdown_pct:'Maximum drawdown (%)',return_over_max_drawdown:'Return / maximum drawdown',profit_factor:'Profit factor',sharpe_trades:'Trade Sharpe ratio',win_rate_pct:'Winning trades (%)',
};
export const builderTermsRu:Record<string,string>={
  limit_scope:'Ограничиваемый ресурс',limit:'Лимит сервера',requested:'Запрошено',used:'Используется',on:'Включено',off:'Выключено',mode:'Режим',coverage_policy:'Политика покрытия',enabled:'Включено',safe_profit_percent:'Безопасная прибыль (%)',
  min_closed_trades:'Минимум закрытых сделок',min_closed_trades_policy:'Политика минимума сделок',base_trades_per_year_at_1h:'Базовое число сделок в год на 1ч',min_trades_per_year:'Минимум сделок в год',max_trades_per_year:'Максимум сделок в год',
  include_when_futures:'Учитывать для фьючерсов',degraded_with_warning:'Предупреждать о неполном покрытии',timeframe_sqrt_v1:'Автоматически · по таймфрейму и периоду',
  indicator_rows:'Строк индикаторов',candidate_combinations:'Комбинаций-кандидатов',tp_sl_cells:'Ячеек TP/SL',cost_class:'Класс затрат',scheduling_class:'Класс исполнения',small:'Малый',medium:'Средний',large:'Большой',light:'Лёгкий',heavy:'Тяжёлый',
  status:'Состояние',coverage_ratio:'Покрытие (%)',rows_count:'Строк фандинга',expected_event_count:'Ожидаемых событий фандинга',missing_event_count:'Пропущенных событий фандинга',warning_codes:'Предупреждения о покрытии',not_applicable:'Не применимо',ready:'Готово',degraded:'Неполное',unavailable:'Недоступно',
  all_in:'Весь доступный капитал',fixed_quote:'Фиксированная сумма',fixed_equity_pct:'Фиксированная доля капитала',fixed_equity_pct_min_quote:'Доля капитала с минимальной суммой',fixed_equity_pct_max_quote:'Доля капитала с максимальной суммой',quote_amount:'Сумма в котируемой валюте',equity_pct:'Доля капитала (%)',min_quote:'Минимальная сумма',max_quote:'Максимальная сумма',
  long_only:'Только лонг',short:'Шорт',long_short_reversal:'Разворот лонг/шорт',none:'Без TP/SL',tp_sl_grid:'Сетка TP/SL',asc:'По возрастанию',desc:'По убыванию',spot:'Спот',futures:'Фьючерсы',
  total_return_pct:'Общая доходность (%)',total_return_pct_net_of_funding:'Доходность после фандинга (%)',max_drawdown_pct:'Максимальная просадка (%)',return_over_max_drawdown:'Доходность / максимальная просадка',profit_factor:'Профит-фактор',sharpe_trades:'Коэффициент Шарпа по сделкам',win_rate_pct:'Прибыльных сделок (%)',
};
