import {ChartDisplayMenu} from './chart-display-menu';
import {ExpandableOverview} from './expandable-overview';
import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react';
import {useTranslation} from 'react-i18next';
import {useNavigate} from 'react-router';
import {useQueryClient} from '@tanstack/react-query';
import {ApiError} from './api';
import {useMotionState} from './motion';
import {ReadError} from './library';
import type {Strategy,readStrategyStatus} from './strategies-api';
import {sendStrategyCommand,type Command,type OperationTrade} from './strategy-operations-api';
import {operationsEn,operationsRu} from './strategy-operations-i18n';
import {releaseRejectedOperation,pendingOperation,retainOperation,releaseOperation} from './operation-recovery';
import {OperationsChart} from './strategy-operations-chart';
type Observation=Awaited<ReturnType<typeof readStrategyStatus>>;
export function StrategyOperations({toolbar,strategy,subject,observation,now,error,children}:{toolbar?:ReactNode;strategy:Strategy;subject:string;observation:Observation|undefined;now:number;error:Error|null;children:ReactNode}){
 const {i18n}=useTranslation();const t=i18n.language.startsWith('ru')?operationsRu:operationsEn;
 const text=useCallback((key:string)=>(t as Record<string,string>)[key]??key,[t]);
 const num=(v:number|null|undefined,d=2)=>v==null?'—':v.toLocaleString(i18n.language,{maximumFractionDigits:d});
 const date=(v:string|null)=>v?new Date(v).toISOString().slice(0,16).replace('T',' '):'—';
 const symbol=strategy.spec.instrument_id.symbol;const quote=['USDT','USDC','USD','BTC','ETH','EUR'].find(q=>symbol.endsWith(q))??'';const base=quote?symbol.slice(0,-quote.length):symbol;
 const [tab,setTab]=useMotionState('price');
 const [tradeSize,setTradeSize]=useState(10);
 const [eventPage,setEventPage]=useState(1),[eventSize,setEventSize]=useState(5);
 const [eventType,setEventType]=useState<string[]|null>(null),[eventReason,setEventReason]=useState<string[]|null>(null);
 const secondary=useRef<HTMLDivElement>(null);
 useEffect(()=>{secondary.current?.scrollTo({top:0});},[tab,eventPage,eventSize]);
 const view=['price','equity','drawdown'].includes(tab)?tab:'price';
 const [selected,setSelected]=useState<string|null>(null),[page,setPage]=useState(1),[filter,setFilter]=useState('all');
 const [command,setCommand]=useState<Command|null>(null),[amount,setAmount]=useState('1000'),[busy,setBusy]=useState(false),[result,setResult]=useState(''),[commandFailure,setFailure]=useState<Error|null>(null),[uncertain,setUncertain]=useState(!!pendingOperation(subject,strategy.strategy_id));
 const dialog=useRef<HTMLDialogElement>(null),lock=useRef(false),mounted=useRef(true),key=useRef('');
 const client=useQueryClient(),navigate=useNavigate();
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>{if(command)dialog.current?.showModal();else dialog.current?.close();},[command]);
 useEffect(()=>{const pending=pendingOperation(subject,strategy.strategy_id);if(!pending)return;const runtime=observation?.runtime_status;const lifecycle=runtime&&Date.parse(runtime.run_updated_at??'')>=(pending.createdAt??Infinity)&&((pending.command==='run'&&runtime.producer_status==='running')||(pending.command==='stop'&&runtime.producer_status==='stopped')||(pending.command==='restart'&&runtime.run_id!==pending.runId&&runtime.producer_status==='running'));if(lifecycle){releaseOperation(subject,strategy.strategy_id);setUncertain(false);setResult('');return;}if(!pending.intent)return;const outcome=observation?.execution_outcomes?.items.find(item=>item.intent_id===pending.intent);if(outcome&&(['filled','cancelled','canceled','rejected','expired'].includes(outcome.order_status??'')||outcome.intent_status==='rejected')){releaseOperation(subject,strategy.strategy_id);setUncertain(false);setResult('');}},[observation,subject,strategy.strategy_id]);
 const data=observation?.operations,account=['ready','degraded'].includes(observation?.paper_accounting?.state??'')?observation?.paper_accounting:undefined;
 const usable=!!observation&&!error&&now-Date.parse(observation.generated_at)<60000;
 const runtime=observation?.runtime_status;const runtimeKnown=runtime&&['ready','degraded'].includes(runtime.state);const running=runtimeKnown&&runtime.producer_status==='running';const state=!runtimeKnown?'unknown':['blocked','unknown'].includes(runtime.producer_status)?runtime.producer_status:runtime.run_state??runtime.producer_status;
 const quantity=account?.state==='ready'||account?.state==='degraded'?account.position_quantity:null;
 const position=quantity!=null&&quantity!==0;const permitted=observation?.selected_strategy.actions;
 const trades=data?.trades??[],closed=trades.filter(v=>v.exit_time!==null),known=closed.filter(v=>v.net_pnl!=null),wins=known.filter(v=>(v.net_pnl??0)>0),losses=known.filter(v=>(v.net_pnl??0)<0);
 const eventKeys=[...trades.flatMap(v=>v.fills.map(f=>`fill:${f.fill_id}`)),...(observation?.signal_journal?.items??[]).map(s=>`signal:${s.bar_ts_close}:${s.signal_action}:${s.outcome}`)];
 const [seen,setSeen]=useState<string[]>(()=>client.getQueryData<string[]>(['private',subject,'read-events',strategy.strategy_id])??[]);
 const unread=eventKeys.filter(key=>!seen.includes(key)).length;
 const eventSignature=JSON.stringify(eventKeys);
 useEffect(()=>{if(tab!=='events'||!unread)return;const next=JSON.parse(eventSignature) as string[];setSeen(next);client.setQueryData(['private',subject,'read-events',strategy.strategy_id],next);},[tab,unread,eventSignature,client,subject,strategy.strategy_id]);
 const eligible=(c:Command)=>usable&&!busy&&!uncertain&&(c==='delete'?permitted?.can_delete&&!running&&quantity===0:c==='run'?permitted?.can_run&&!running:c==='stop'||c==='restart'?permitted?.can_stop&&running:c==='manual-entry'?running&&!!runtime?.run_id&&!!data?.current_price&&quantity===0:running&&!!runtime?.run_id&&!!data?.current_price&&position);
 const refresh=async()=>{await client.invalidateQueries({queryKey:['private',subject,'strategy-status',strategy.strategy_id]});};
 function choose(c:Command){if(!eligible(c))return;key.current=crypto.randomUUID();setFailure(null);setResult('');setCommand(c);}
 async function submit(){if(!command||lock.current||!eligible(command))return;const action=command;retainOperation({subject,strategy:strategy.strategy_id,key:key.current,command:action,amount:Number(amount),price:data?.current_price??undefined,createdAt:Date.now(),runId:observation?.runtime_status.run_id});lock.current=true;setBusy(true);setFailure(null);try{
  const reply=await sendStrategyCommand(strategy.strategy_id,action,key.current,Number(amount),observation?.runtime_status.run_id,data?.current_price??undefined);
  const unresolved=reply.status==='unknown'||reply.status==='pending'||(action.startsWith('manual-')&&!('terminal' in reply&&reply.terminal));
  if(unresolved){retainOperation({...pendingOperation(subject,strategy.strategy_id),subject,strategy:strategy.strategy_id,key:key.current,...('intent' in reply?{intent:reply.intent}:{})});}else releaseOperation(subject,strategy.strategy_id);
  if(!mounted.current)return;setResult(reply.status==='unknown'?'unknownOutcome':reply.status==='rejected'?'rejected':reply.status==='pending'?'pending':'accepted');setUncertain(unresolved);setCommand(null);
  await refresh();if(action==='delete'){await client.invalidateQueries({queryKey:['private',subject,'strategies']});void navigate('/strategies');}
 }catch(e){if(!(e instanceof ApiError)||e.outcome==='unknown'){}else releaseOperation(subject,strategy.strategy_id);if(mounted.current){setFailure(e as Error);if(!(e instanceof ApiError)||e.outcome==='unknown'){setUncertain(true);setResult('unknownOutcome');}setCommand(null);}}finally{lock.current=false;if(mounted.current)setBusy(false);}}
 async function reconcile(){const pending=pendingOperation(subject,strategy.strategy_id);if(!pending?.runId||!pending.price||!pending.command?.startsWith('manual-')){await refresh();return;}if(lock.current)return;lock.current=true;setBusy(true);try{const reply=await sendStrategyCommand(strategy.strategy_id,pending.command,pending.key,pending.amount,pending.runId,pending.price);if('terminal' in reply&&reply.terminal){releaseOperation(subject,strategy.strategy_id);if(mounted.current){setUncertain(false);setResult(reply.status==='rejected'?'rejected':'accepted');}}else if('intent' in reply){retainOperation({...pending,intent:reply.intent});}await refresh();}catch(e){const released=releaseRejectedOperation(subject,strategy.strategy_id,e);if(mounted.current){setFailure(e as Error);if(released){setUncertain(false);setResult('');}}}finally{lock.current=false;if(mounted.current)setBusy(false);}}
 const events=[
  ...trades.flatMap(trade=>trade.fills.map(fill=>({id:'fill:'+fill.fill_id,time:fill.time,type:fill.action,action:fill.side.toUpperCase()+' · '+num(fill.quantity,6),reason:fill.reason,price:fill.price}))),
  ...(observation?.signal_journal?.items??[]).map((signal,index)=>({id:'signal:'+index,time:signal.bar_ts_close,type:'signal',action:signal.signal_action,reason:signal.outcome,price:signal.reference_price}))
 ].sort((a,b)=>Date.parse(b.time)-Date.parse(a.time));
 const eventReasons=[...new Set(events.map(event=>event.reason))];
 const visibleEvents=events.filter(event=>(eventType===null||eventType.includes(event.type))&&(eventReason===null||eventReason.includes(event.reason)));
 const filtered=trades.filter(v=>filter==='all'||v.side===filter);const shown=filtered.slice((page-1)*tradeSize,page*tradeSize);
 function select(id:string){setSelected(id);setTab('trades');const index=filtered.findIndex(t=>t.trade_id===id);if(index>=0)setPage(Math.floor(index/tradeSize)+1);}
 const lifecycle=<div className="operations-lifecycle"><button disabled={!eligible(running?'stop':'run')} onClick={()=>choose(running?'stop':'run')}>{running?t.stop:t.run}</button><button className="danger" disabled={!eligible('delete')} onClick={()=>choose('delete')}>{t.delete}</button></div>;
 return <div className="operations-workspace" onPointerDownCapture={event=>{if(event.target instanceof Element){const control=event.target.closest('select,.overview-expand');if(control instanceof HTMLElement)control.dataset.pointerFocus='true';}}} onKeyDownCapture={event=>{if(event.target instanceof HTMLElement)delete event.target.dataset.pointerFocus;}}>
  <header className="operations-header"><div><h2 id="selected-strategy-heading" tabIndex={-1}>{strategy.name}</h2></div><div className="operations-actions"><span className={`operation-state operations-state-badge ${running?'is-running':''}`}><span aria-hidden="true">●</span> {text(state)}</span>{toolbar}</div></header>
  <ReadError error={error}/><ReadError error={commandFailure}/>{(result||uncertain)&&<p role="status" className="notice">{text(result||'unknownOutcome')}{uncertain&&<button disabled={busy} onClick={()=>void reconcile()}>{t.checkOutcome}</button>}</p>}
  <div className="operations-metrics">{[[t.capital,account?.pnl_complete?account.equity:null],[t.closedPnl,account?.pnl_complete?account.realized_pnl:null],[t.openPnl,account?.pnl_complete?account.unrealized_pnl:null],[t.fees,account?.fee_total],[t.drawdown,data?.partial||!data?.drawdown.length?null:Math.min(...data.drawdown.map(v=>v.value))]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{num(typeof value==='number'?value:null)}</strong></div>)}</div>
  {data?.partial&&<p className="freshness">{t.partial}</p>}
  <ExpandableOverview className="operations-overview" label={t.title} controls={<div className="operations-view-tools"><div className="result-tabs" role="tablist" aria-label={t.title}>{['price','equity','drawdown','trades','events'].map((name,index)=><button key={name} role="tab" id={`operations-${name}`} aria-controls={['trades','events'].includes(name)?'operations-detail':'operations-chart-panel'} aria-selected={tab===name} tabIndex={tab===name?0:-1} onClick={()=>setTab(name)} onKeyDown={event=>{const names=['price','equity','drawdown','trades','events'];const n=event.key==='ArrowRight'?(index+1)%5:event.key==='ArrowLeft'?(index+4)%5:-1;if(n>=0){event.preventDefault();setTab(names[n]!);document.getElementById(`operations-${names[n]}`)?.focus();}}}>{text(name)}{name==='trades'&&` · ${trades.length}`}{name==='events'&&unread>0&&<span className="events-unread" aria-label={`${unread} ${i18n.language.startsWith('ru')?'непрочитанных':'unread'}`}>{unread>99?'99+':unread}</span>}</button>)}</div></div>}>
  <div className="operations-stage" data-motion-content data-motion-style="smooth">
  <div className={`operations-main${tab==='price'?'':' operations-chart-only'}`} hidden={! ['price','equity','drawdown'].includes(tab)} role="tabpanel" id="operations-chart-panel" aria-labelledby={`operations-${tab}`}><section className="operations-market">{data&&data.state!=='unavailable'?<><OperationsChart sourceTimeframe={strategy.spec.timeframe} candles={observation?.chart?.candles??[]} data={data} view={view} selected={selected} onSelect={select} reason={text} label={text(view)}/>{view==='price'&&!observation?.chart?.candles.length&&<p className="notice">{t.noCandles}</p>}</>:<p className="operations-chart-empty">{t.unavailable}</p>}</section>
  {tab==='price'&&<aside className="operations-position"><div className="panel-head"><h3>{t.position}</h3>{position&&<span className="operation-state is-running">{quantity!>0?'LONG':'SHORT'}</span>}</div>{quantity==null?<p>{t.unavailable}</p>:!position?<p>{t.noPosition}</p>:<dl>{[[`${t.quantity} · ${base}`,num(Math.abs(quantity),6)],[t.entry,num(account?.average_entry_price)],[t.mark,num(data?.current_price)],[`${t.notional} · ${quote}`,num(data?.current_price==null?null:Math.abs(quantity)*data.current_price)],[t.openPnl,num(account?.unrealized_pnl)],[t.stopLoss,data?.stop_loss==null?t.unconfigured:num(data.stop_loss)],[t.takeProfit,data?.take_profit==null?t.unconfigured:num(data.take_profit)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}<button className="primary" disabled={!eligible('manual-exit')} onClick={()=>choose('manual-exit')}>{t.manualExit}</button><button disabled={!eligible('manual-entry')} onClick={()=>choose('manual-entry')}>{t.manualEntry}</button>{tab==='price'&&lifecycle}</aside>}</div>
  <div ref={secondary} className="operations-secondary" hidden={tab!=='trades'&&tab!=='events'}>
  <div id="operations-detail" role="tabpanel" aria-labelledby={`operations-${tab}`}>

  {tab==='events'&&<><div className="operations-trade-tools"><ChartDisplayMenu multiple label={t.eventType} value={eventType===null?t.allEvents:`${t.eventType} · ${eventType.length}`} options={[{label:t.allEvents,checked:eventType===null,onChange:(checked)=>{setEventType(checked?null:[]);setEventPage(1);}},...[{value:'entry',label:t.entryAction},{value:'exit',label:t.exitAction},{value:'signal',label:t.signal}].map(option=>({label:option.label,checked:eventType===null||eventType.includes(option.value),onChange:(checked:boolean)=>{setEventType(current=>{const next=checked?[...(current??[]),option.value]:(current??['entry','exit','signal']).filter(value=>value!==option.value);return next.length===3?null:next;});setEventPage(1);}}))]}/><ChartDisplayMenu multiple label={t.reason} value={eventReason===null?t.allReasons:`${t.reason} · ${eventReason.length}`} options={[{label:t.allReasons,checked:eventReason===null,onChange:(checked)=>{setEventReason(checked?null:[]);setEventPage(1);}},...eventReasons.map(reason=>({label:text(reason),checked:eventReason===null||eventReason.includes(reason),onChange:(checked:boolean)=>{setEventReason(current=>{const next=checked?[...(current??[]),reason]:(current??eventReasons).filter(value=>value!==reason);return next.length===eventReasons.length?null:next;});setEventPage(1);}}))]}/></div><div className="table-scroll" tabIndex={0}><table className="operations-events"><thead><tr><th>{t.fillTime}</th><th>{t.actions}</th><th>{t.reason}</th><th>{t.fillPrice}</th></tr></thead><tbody>{visibleEvents.slice((eventPage-1)*eventSize,eventPage*eventSize).map(event=><tr key={event.id}><td>{date(event.time)}</td><td>{event.type==='signal'?text('signal')+' · ':''}{event.action}</td><td>{text(event.reason)}</td><td>{num(event.price)}</td></tr>)}</tbody></table></div>{!visibleEvents.length&&<p>{t.noEvents}</p>}<TablePagination page={eventPage} size={eventSize} total={visibleEvents.length} setPage={setEventPage} setSize={setEventSize} text={text}/></>}
  {tab==='trades'&&<><div className="operations-trade-tools"><ChartDisplayMenu label={t.direction} value={filter==='all'?'Long / Short':filter==='long'?'Long':'Short'} options={[{value:'all',label:'Long / Short'},{value:'long',label:'Long'},{value:'short',label:'Short'}].map(option=>({label:option.label,checked:filter===option.value,onChange:()=>{setFilter(option.value);setPage(1);}}))}/><span>{t.count}: {closed.length}</span><span>{t.winRate}: {known.length===closed.length&&known.length>0&&!data?.partial?`${num(wins.length/known.length*100)}%`:'—'}</span><span>{t.profitFactor}: {known.length===closed.length&&losses.length>0&&!data?.partial?num(wins.reduce((s,v)=>s+v.net_pnl!,0)/-losses.reduce((s,v)=>s+v.net_pnl!,0)):'—'}</span></div><div className="table-scroll" tabIndex={0}><table className="operations-trades"><thead><tr>{[t.direction,t.entryTime,t.exitTime,`${t.quantity} · ${base} / ${quote}`,t.entryReason,t.exitReason,t.net].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{shown.map(trade=><TradeRows key={trade.trade_id} trade={trade} selected={selected===trade.trade_id} onSelect={()=>setSelected(selected===trade.trade_id?null:trade.trade_id)} text={text} num={num} date={date} base={base} quote={quote}/>)}</tbody></table></div>{!trades.length&&<p>{t.emptyTrades}</p>}<TablePagination page={page} size={tradeSize} total={filtered.length} setPage={setPage} setSize={setTradeSize} text={text}/></>}
  </div></div>
  </div>
  <div className="operations-footer"><div className="operations-technical">{children}</div><div className="operations-metadata"><p className="muted">{strategy.spec.instrument_key} · {strategy.spec.timeframe} · {data?.source==='synthetic_demo'?t.demo:observation?.runtime_status.environment??'—'}</p><p className="freshness">{observation?`${t.updated} · ${date(observation.generated_at)} UTC`:t.loading}{!usable&&` · ${t.stateUnavailable}`}</p></div></div>
  <dialog ref={dialog} className="operation-dialog" onCancel={()=>{if(!busy)setCommand(null);}}><form onSubmit={e=>{e.preventDefault();void submit();}}><h3>{command?text(command==='manual-entry'?'manualEntry':command==='manual-exit'?'manualExit':command):''}</h3><p>{strategy.name}</p><p>{command==='stop'||command==='restart'?t.stopHelp:command==='delete'?t.deleteHelp:t.manualHelp}</p>{command==='manual-entry'&&<label>{t.amount}<input type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label>}<div className="actions"><button type="button" disabled={busy} onClick={()=>setCommand(null)}>{t.cancel}</button><button className="primary" disabled={busy} type="submit">{busy?'…':t.confirm}</button></div></form></dialog>
 </ExpandableOverview></div>;
}
function TradeRows({trade:v,selected,onSelect,text,num,date,base,quote}:{base:string;quote:string;trade:OperationTrade;selected:boolean;onSelect:()=>void;text:(k:string)=>string;num:(n:number|null|undefined,d?:number)=>string;date:(v:string|null)=>string}){return <><tr className={selected?'selected':''}><td><button onClick={onSelect} aria-expanded={selected}>{v.side.toUpperCase()}</button></td><td>{num(v.entry)}<small>{date(v.entry_time)}</small></td><td>{num(v.exit)}<small>{v.exit_time?date(v.exit_time):text('open')}</small></td><td>{num(v.quantity,6)} {base}<small>{num(v.fills.filter(f=>f.action==='entry').reduce((sum,f)=>sum+f.quantity*f.price,0))} {quote}</small></td><td>{text(v.entry_reason)}</td><td>{v.exit_reason?text(v.exit_reason):'—'}</td><td className={(v.net_pnl??0)<0?'pnl-negative':'pnl-positive'}>{v.exit_time?num(v.net_pnl):'—'}</td></tr>{selected&&<tr><td colSpan={7}><div className="operations-trade-detail"><strong>{text('gross')}: {num(v.gross_pnl)} · {text('fees')}: {num(v.fees)} · {text('net')}: {num(v.net_pnl)}</strong><p>{text('duration')}: {v.exit_time?num((Date.parse(v.exit_time)-Date.parse(v.entry_time))/60000):'—'} min</p><table><thead><tr>{['fillTime','actions','quantity','fillPrice','signalPrice','slippage','fees','reason'].map(k=><th key={k}>{k==='quantity'?`${text(k)} · ${base}`:k==='fillPrice'||k==='signalPrice'||k==='fees'?`${text(k)} · ${quote}`:text(k)}</th>)}</tr></thead><tbody>{v.fills.map(f=><tr key={f.fill_id}><td>{date(f.time)}</td><td>{text(f.action==='entry'?'entryAction':'exitAction')}</td><td>{num(f.quantity,6)}</td><td>{num(f.price)}</td><td>{num(f.reference_price)}</td><td>{f.reference_price!=null&&f.reference_price>0?num((f.price-f.reference_price)/f.reference_price*(f.side==='buy'?1:-1)*100,4):'—'}</td><td>{num(f.fee)}</td><td>{text(f.reason)}</td></tr>)}</tbody></table></div></td></tr>}</>}

function TablePagination({page,size,total,setPage,setSize,text}:{page:number;size:number;total:number;setPage:(n:number)=>void;setSize:(n:number)=>void;text:(key:string)=>string}){
 return <nav className="pagination operations-event-pagination"><label>{text('rowsPerPage')}<select aria-label={text('rowsPerPage')} value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[5,10,25,50].map(n=><option key={n} value={n}>{n}</option>)}</select></label><span>{total?(page-1)*size+1:0}–{Math.min(page*size,total)} / {total}</span><button aria-label={text('previousPage')} disabled={page===1} onClick={()=>setPage(page-1)}>←</button><span>{page} / {Math.max(1,Math.ceil(total/size))}</span><button aria-label={text('nextPage')} disabled={page*size>=total} onClick={()=>setPage(page+1)}>→</button></nav>;
}
