apiVersion: 1

datasources:
  - access: proxy
    editable: false
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 30s
    name: Roehub Prometheus
    orgId: 1
    type: prometheus
    uid: roehub-prometheus
    url: http://prometheus:9090
    version: 1
