"""DTO package for the reset backtest scope."""

from .combo_planning import (
    BacktestComboChunk,
    BacktestComboPlanningConfig,
    BacktestComboPlanningResult,
    BacktestComboPlanningTelemetry,
    BacktestExactContext,
    BacktestProxyContext,
    BacktestProxyFilterResult,
    BacktestSelectedBackend,
)
from .no_risk_exact import (
    BacktestNoRiskExactConfig,
    BacktestNoRiskExactResult,
    BacktestNoRiskExactTelemetry,
    BacktestNoRiskExecutionContext,
    BacktestNoRiskMemoryCleanupEvidence,
    BacktestNoRiskSelfCheckSummary,
    BacktestNoRiskTopResult,
    CompactScalar,
    canonical_no_risk_json_hash,
    canonical_no_risk_top_results_hash,
    canonical_no_risk_top_results_payload,
)
from .prepare_pools import (
    BacktestPreparePoolsConfig,
    BacktestPreparePoolsResult,
    PreparedExecutionMapping,
    PreparedIndicatorPool,
    PreparedIndicatorRowMetadata,
    PreparedSignalSegments,
    PreparePoolsTiming,
)
from .runtime_preflight import (
    BacktestArtifactMetadata,
    BacktestCoordinates,
    BacktestCostEstimate,
    BacktestExecutionDefaults,
    BacktestPreflightResult,
    BacktestRuntimeDefaults,
    BacktestRuntimeGuardrails,
    BacktestValidationIssue,
    JsonMapping,
)

__all__ = [
    "BacktestArtifactMetadata",
    "BacktestComboChunk",
    "BacktestComboPlanningConfig",
    "BacktestComboPlanningResult",
    "BacktestComboPlanningTelemetry",
    "BacktestCoordinates",
    "BacktestCostEstimate",
    "BacktestExecutionDefaults",
    "BacktestExactContext",
    "BacktestNoRiskExactConfig",
    "BacktestNoRiskExactResult",
    "BacktestNoRiskExactTelemetry",
    "BacktestNoRiskExecutionContext",
    "BacktestNoRiskMemoryCleanupEvidence",
    "BacktestNoRiskSelfCheckSummary",
    "BacktestNoRiskTopResult",
    "BacktestPreparePoolsConfig",
    "BacktestPreparePoolsResult",
    "BacktestPreflightResult",
    "BacktestProxyContext",
    "BacktestProxyFilterResult",
    "BacktestRuntimeDefaults",
    "BacktestRuntimeGuardrails",
    "BacktestSelectedBackend",
    "BacktestValidationIssue",
    "CompactScalar",
    "JsonMapping",
    "PreparedExecutionMapping",
    "PreparedIndicatorPool",
    "PreparedIndicatorRowMetadata",
    "PreparedSignalSegments",
    "PreparePoolsTiming",
    "canonical_no_risk_json_hash",
    "canonical_no_risk_top_results_hash",
    "canonical_no_risk_top_results_payload",
]
