"""Add Backtest AI conversation storage."""

from __future__ import annotations

from alembic import op

revision = "20260518_0014"
down_revision = "20260511_0013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS backtest_ai_conversations (
            conversation_id UUID PRIMARY KEY,
            owner_user_id UUID NOT NULL,
            locale TEXT NOT NULL,
            status TEXT NOT NULL,
            title TEXT NOT NULL,
            title_source TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            last_message_at TIMESTAMPTZ NOT NULL,
            expires_at TIMESTAMPTZ NOT NULL,
            CONSTRAINT backtest_ai_conversations_locale_chk
                CHECK (locale IN ('ru', 'en')),
            CONSTRAINT backtest_ai_conversations_status_chk
                CHECK (status IN ('active', 'archived')),
            CONSTRAINT backtest_ai_conversations_title_source_chk
                CHECK (title_source IN ('fallback', 'model')),
            CONSTRAINT backtest_ai_conversations_title_chk
                CHECK (
                    btrim(title) <> ''
                    AND length(title) <= 80
                    AND title !~ '[[:cntrl:]<>]'
                ),
            CONSTRAINT backtest_ai_conversations_retention_chk
                CHECK (expires_at > created_at)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_backtest_ai_conversations_owner_active
            ON backtest_ai_conversations
                (owner_user_id, last_message_at DESC, conversation_id DESC)
            WHERE status = 'active'
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_backtest_ai_conversations_expires
            ON backtest_ai_conversations (expires_at ASC)
            WHERE status = 'active'
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS backtest_ai_conversation_messages (
            message_id UUID PRIMARY KEY,
            message_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
            conversation_id UUID NOT NULL REFERENCES backtest_ai_conversations
                (conversation_id) ON DELETE CASCADE,
            owner_user_id UUID NOT NULL,
            role TEXT NOT NULL,
            content TEXT NOT NULL,
            metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL,
            CONSTRAINT backtest_ai_conversation_messages_role_chk
                CHECK (role IN ('system', 'assistant', 'user')),
            CONSTRAINT backtest_ai_conversation_messages_content_chk
                CHECK (btrim(content) <> '' AND length(content) <= 16000),
            CONSTRAINT backtest_ai_conversation_messages_metadata_chk
                CHECK (jsonb_typeof(metadata_json) = 'object')
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_backtest_ai_conversation_messages_conversation_seq
            ON backtest_ai_conversation_messages
                (conversation_id, message_seq ASC, message_id ASC)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_backtest_ai_conversation_messages_owner_created
            ON backtest_ai_conversation_messages
                (owner_user_id, created_at DESC, message_id DESC)
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS backtest_ai_conversation_runs (
            run_id UUID PRIMARY KEY,
            conversation_id UUID NOT NULL REFERENCES backtest_ai_conversations
                (conversation_id) ON DELETE CASCADE,
            owner_user_id UUID NOT NULL,
            user_message_id UUID NOT NULL REFERENCES backtest_ai_conversation_messages
                (message_id) ON DELETE CASCADE,
            assistant_message_id UUID NOT NULL REFERENCES backtest_ai_conversation_messages
                (message_id) ON DELETE CASCADE,
            status TEXT NOT NULL,
            intent TEXT NULL,
            load_action_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            current_config_json JSONB NULL,
            validated_config_json JSONB NULL,
            model_id TEXT NULL,
            failure_reason TEXT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            CONSTRAINT backtest_ai_conversation_runs_status_chk
                CHECK (
                    status IN (
                        'awaiting_model',
                        'ready',
                        'needs_clarification',
                        'blocked_by_policy',
                        'failed'
                    )
                ),
            CONSTRAINT backtest_ai_conversation_runs_intent_chk
                CHECK (intent IS NULL OR btrim(intent) <> ''),
            CONSTRAINT backtest_ai_conversation_runs_load_action_chk
                CHECK (jsonb_typeof(load_action_json) = 'object'),
            CONSTRAINT backtest_ai_conversation_runs_current_config_chk
                CHECK (
                    current_config_json IS NULL
                    OR jsonb_typeof(current_config_json) = 'object'
                ),
            CONSTRAINT backtest_ai_conversation_runs_validated_config_chk
                CHECK (
                    validated_config_json IS NULL
                    OR jsonb_typeof(validated_config_json) = 'object'
                )
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_backtest_ai_conversation_runs_conversation_created
            ON backtest_ai_conversation_runs
                (conversation_id, created_at DESC, run_id DESC)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_backtest_ai_conversation_runs_owner_created
            ON backtest_ai_conversation_runs
                (owner_user_id, created_at DESC, run_id DESC)
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS backtest_ai_conversation_runs")
    op.execute("DROP TABLE IF EXISTS backtest_ai_conversation_messages")
    op.execute("DROP TABLE IF EXISTS backtest_ai_conversations")
