import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
const root=resolve(import.meta.dirname,'../../..');
const evidence=resolve(root,process.env.ROEHUB_PROOF_EVIDENCE??'.local_artifacts/strategy-insights-proof','insights');
test('saved backtest remains accessible separately; standalone strategy contains only operational data',async({page})=>{
 test.setTimeout(150000);mkdirSync(evidence,{recursive:true});
 const errors:string[]=[];const commands:string[]=[];
 page.on('pageerror',()=>errors.push('pageerror'));
 expect((await page.request.get(`/api/strategies/${randomUUID()}/research-source`)).status()).toBe(401);
 await page.goto('/strategies');
 const credentials=JSON.parse(readFileSync(resolve(root,process.env.ROEHUB_PROOF_STATE??'.local_artifacts/backtests-client','credentials.json'),'utf8'));
 const form=page.locator('[data-password-login]');await form.locator('..').locator('summary').click();await form.locator('[name=username]').fill(credentials.username);await form.locator('[name=password]').fill(credentials.password);await form.locator('button[type=submit]').click();
 await expect(page.locator('[data-platform-client]')).toBeVisible();
 const defaults=await (await page.request.get('/api/backtests/runtime-defaults')).json();
 const body={strategy_name:'Strategy analysis proof',coordinates:{exchange:'binance',market_type:'spot',symbol:'BTCUSDT'},timeframe:'15m',time_range:{start:'2026-03-26T00:00:00Z',end:'2026-03-29T00:00:00Z'},indicators:[{indicator_id:'ma.ema',sources:['close'],window:{start:10,stop:10,step:1}}],risk:{mode:'none'},execution:{...defaults.execution_defaults,direction_mode:'long_only'},ranking:defaults.ranking_default,top_n:defaults.top_n_default,quality_constraints:defaults.quality_constraints_default};
 const preflight=await page.request.post('/api/backtests/preflight',{data:body});expect(preflight.status()).toBe(200);expect((await preflight.json()).errors).toEqual([]);
 const created=await page.request.post('/api/backtests/jobs',{data:body,headers:{'Idempotency-Key':randomUUID()}});expect(created.status()).toBe(201);const job=(await created.json()).job_id;
 await expect.poll(async()=>(await (await page.request.get(`/api/backtests/jobs/${job}`)).json()).state,{timeout:60000}).toBe('succeeded');
 const summary=await (await page.request.get(`/api/backtests/jobs/${job}/summary`)).json();const variant=summary.selected_variant_key;
 const saved=await page.request.post(`/api/backtests/jobs/${job}/variants/${encodeURIComponent(variant)}/strategies`,{headers:{'Idempotency-Key':randomUUID()}});expect(saved.status()).toBe(201);const id=(await saved.json()).strategy.strategy_id;
 const source=await page.request.get(`/api/strategies/${id}/research-source`);expect(source.status()).toBe(200);expect(await source.json()).toEqual({strategy_id:id,source_job_id:job,source_variant_key:variant});
 page.on('request',request=>{if(request.method()!=='GET'&&new URL(request.url()).pathname.startsWith('/api/'))commands.push(new URL(request.url()).pathname);});
 const researchReads:string[]=[];page.on('request',r=>{if(/research-source|\/api\/backtests\//.test(r.url()))researchReads.push(new URL(r.url()).pathname);});
 await page.goto(`/strategies/${id}`);await expect(page.locator('#selected-strategy-heading')).toBeVisible();await page.reload();await expect(page.locator('.operations-workspace')).toBeVisible();
 await expect(page.getByRole('tab',{name:'Backtest',exact:true})).toHaveCount(0);await expect(page.locator('.strategy-research-metrics')).toHaveCount(0);
 await page.getByRole('tab',{name:'Settings',exact:true}).click();await expect(page.getByText('EMA · Exponential moving average',{exact:true})).toBeVisible();
 await page.getByRole('tab',{name:'Settings',exact:true}).press('ArrowLeft');await expect(page.getByRole('tab',{name:'Events',exact:true})).toBeFocused();
 expect(researchReads).toEqual([]);expect(commands).toEqual([]);expect(errors).toEqual([]);
 await page.screenshot({path:resolve(evidence,'saved-strategy-operations.png'),fullPage:true});
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
 writeFileSync(resolve(evidence,'observations.json'),JSON.stringify({job,variant,strategy:id,sourceStatus:200,standaloneReload:true,noResearchReads:true,commands,errors},null,2));
});
