async page => {
 const check=(condition,message)=>{if(!condition)throw new Error(message);};
 await page.locator('.overview-summary').waitFor();
 const equity=()=>page.locator('.overview-equity strong').innerText();
 const total=await equity();
 await page.getByLabel('Portfolio',{exact:true}).selectOption('Binance');
 check(await page.locator('.overview-contributions tbody tr').count()===3,'Binance membership');
 check(!(await page.locator('.overview-contributions').innerText()).includes('Ether Swing'),'Cross-exchange leakage in fixture');
 await page.getByLabel('Portfolio',{exact:true}).selectOption('ETHUSDT');
 check(await page.locator('.overview-contributions tbody tr').count()===2,'Instrument membership');
 check((await page.locator('.overview-summary').innerText()).includes('No separate cash attribution'),'Scope cash must be unavailable');
 await page.getByLabel('Portfolio',{exact:true}).selectOption('total');
 await page.getByRole('button',{name:'Paper',exact:true}).click();check(await equity()!==total,'Paper must be separate');
 await page.getByRole('button',{name:'Live',exact:true}).click();check(await equity()===total,'Live restored');
 await page.getByRole('button',{name:'1W',exact:true}).click();check(await equity()===total,'Current equity must ignore historical period');
 await page.getByRole('button',{name:'Custom',exact:true}).click();
 await page.getByLabel('From',{exact:true}).fill('2026-08-01');await page.getByLabel('To',{exact:true}).fill('2026-08-15');
 check(await equity()===total,'Custom past range must preserve current equity');
 await page.getByRole('button',{name:'YTD',exact:true}).click();
 await page.getByRole('button',{name:'Return',exact:true}).click();await page.getByLabel('Compare strategies',{exact:true}).check();
 check(await page.locator('.overview-legend span').count()===4,'Comparison legend');
 await page.getByRole('button',{name:'Drawdown',exact:true}).click();
 await page.getByRole('button',{name:'Expand chart',exact:true}).click();check(await page.locator('.overview-expanded').count()===1,'Expansion');
 await page.keyboard.press('Escape');check(await page.locator('.overview-expanded').count()===0,'Escape collapse');
 await page.getByRole('button',{name:'Equity',exact:true}).click();
 await page.getByRole('button',{name:'Atlas Momentum Binance · BTCUSDT',exact:true}).click();
 await page.getByRole('button',{name:'Inspect this strategy',exact:true}).click();check(await page.locator('.overview-contributions tbody tr').count()===1,'Strategy drilldown');
 await page.getByRole('button',{name:'Reset',exact:true}).click();
 await page.getByRole('button',{name:'Instruments',exact:true}).click();
 check((await page.locator('.overview-allocation').innerText()).includes('41,500.00 / 5,500.00'),'Offsetting ETH gross/net');
 await page.getByRole('button',{name:'Exchanges',exact:true}).click();
 await page.getByRole('button',{name:'Recent trades',exact:true}).click();
 const first=await page.locator('.overview-activity tbody tr').first().innerText();
 await page.getByRole('button',{name:'Next page',exact:true}).click();check(await page.locator('.overview-activity tbody tr').first().innerText()!==first,'Pagination');
 await page.getByRole('button',{name:'Previous page',exact:true}).click();
 await page.locator('.overview-activity tbody summary').first().click();check(await page.getByText('2 partial fills · one order',{exact:true}).first().isVisible(),'Partial fills');
 await page.getByRole('button',{name:'Positions',exact:true}).click();
 await page.getByRole('button',{name:'Create portfolio',exact:true}).click();
 await page.getByRole('button',{name:'Save portfolio',exact:true}).click();check(await page.getByRole('alert').isVisible(),'Basket validation');
 await page.getByLabel('Portfolio name',{exact:true}).fill('QA cross-exchange');
 await page.locator('.overview-member').filter({hasText:'Atlas Momentum'}).locator('input').check();
 await page.locator('.overview-member').filter({hasText:'Ether Swing'}).locator('input').check();
 await page.getByRole('button',{name:'Save portfolio',exact:true}).click();
 const basket=await page.getByLabel('Portfolio',{exact:true}).inputValue();check(basket.startsWith('custom-'),'Basket created');
 await page.reload();await page.locator('.overview-summary').waitFor();
 check(await page.getByLabel('Portfolio',{exact:true}).inputValue()===basket,'Selected basket restored');
 check(await page.locator('.overview-contributions tbody tr').count()===2,'Membership restored');
 await page.getByRole('button',{name:'Edit portfolio',exact:true}).click();
 await page.getByLabel('Portfolio name',{exact:true}).fill('QA renamed');
 await page.locator('.overview-member').filter({hasText:'Delta Neutral'}).locator('input').check();
 await page.getByRole('button',{name:'Save portfolio',exact:true}).click();
 check(await page.locator('.overview-contributions tbody tr').count()===3,'Membership edit');
 await page.getByRole('button',{name:'Edit portfolio',exact:true}).click();
 await page.getByRole('button',{name:'Delete portfolio',exact:true}).click();
 check(await page.getByLabel('Portfolio',{exact:true}).inputValue()==='total','Deleted selection recovery');
 await page.reload();await page.locator('.overview-summary').waitFor();
 check(await page.getByLabel('Portfolio',{exact:true}).locator('option').count()===6,'Delete persisted');
 await page.locator('.overview-demo-tools summary').click();
 for(const state of ['empty','no-activity','history','partial','stale','error']){
  await page.getByLabel('Data state',{exact:true}).selectOption(state);
  await page.screenshot({path:'.codex/delivery/evidence/roehub-overview-2026-09-26/state-'+state+'.png',fullPage:true});
 }
 await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('status').waitFor();await page.locator('.overview-summary').waitFor();
 await page.getByLabel('Data state',{exact:true}).selectOption('refresh');
 check(await page.locator('.overview-summary').isVisible(),'Refresh retains values');await page.getByRole('status').waitFor({state:'hidden'});
 await page.locator('.overview-demo-tools summary').click();
 return {result:'passed',checks:'Scopes, current/period separation, modes, comparisons, fullscreen, drilldown, gross/net, pagination, fills, basket CRUD/reload, validation, deleted recovery, empty/history/partial/stale/error/retry/loading/refresh'};
}
