"""
Adapters package for identity bounded context.
"""

from .inbound import (
    CurrentUserResponse,
    RequireCurrentUserDependency,
    RequireTwoFactorEnabledDependency,
    TelegramLoginRequest,
    TelegramLoginResponse,
    TwoFactorRequiredHttpError,
    TwoFactorSetupResponse,
    TwoFactorVerifyRequest,
    TwoFactorVerifyResponse,
    build_auth_telegram_router,
    build_two_factor_totp_router,
    register_two_factor_required_exception_handler,
)
from .outbound import (
    AesGcmEnvelopeTwoFactorSecretCipher,
    Hs256JwtCodec,
    IdentityPostgresGateway,
    InMemoryIdentityTwoFactorRepository,
    InMemoryIdentityUserRepository,
    JwtCookieCurrentUser,
    PostgresIdentityTwoFactorRepository,
    PostgresIdentityUserRepository,
    PsycopgIdentityPostgresGateway,
    PyOtpTwoFactorTotpProvider,
    RepositoryTwoFactorPolicyGate,
    SystemIdentityClock,
    TelegramLoginWidgetPayloadValidator,
)

__all__ = [
    "AesGcmEnvelopeTwoFactorSecretCipher",
    "CurrentUserResponse",
    "Hs256JwtCodec",
    "IdentityPostgresGateway",
    "InMemoryIdentityTwoFactorRepository",
    "InMemoryIdentityUserRepository",
    "JwtCookieCurrentUser",
    "PostgresIdentityTwoFactorRepository",
    "PostgresIdentityUserRepository",
    "PyOtpTwoFactorTotpProvider",
    "PsycopgIdentityPostgresGateway",
    "RequireCurrentUserDependency",
    "RequireTwoFactorEnabledDependency",
    "RepositoryTwoFactorPolicyGate",
    "SystemIdentityClock",
    "TelegramLoginRequest",
    "TelegramLoginResponse",
    "TelegramLoginWidgetPayloadValidator",
    "TwoFactorRequiredHttpError",
    "TwoFactorSetupResponse",
    "TwoFactorVerifyRequest",
    "TwoFactorVerifyResponse",
    "build_auth_telegram_router",
    "build_two_factor_totp_router",
    "register_two_factor_required_exception_handler",
]
