import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link,useSearchParams} from 'react-router';
import {useQueries,useQuery,useQueryClient} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {ArrowDown,ArrowUp,ArrowUpDown,CheckCircle2,ChevronDown,ChevronLeft,ChevronRight,Circle,Clock3,Download,LockKeyhole,Search,TriangleAlert,X} from 'lucide-react';
import {readMarkets,type Market} from './connections-api';
import {ApiError} from './api';
import {closedDayRange,rangeIso,selectInstrument,validateCoverageRange,validateWorkRange,type WorkJob} from './market-data-api';
import {readDataInspector,readExchangeCatalog,readHistoryBounds,type CatalogRow,type DataInspector} from './data-workspace-api';
import {useReadSnapshot} from './read-snapshot';
import {CollectionLibrary,deniesRead,DirtyGuard,Field,formatTime,ReadFeedback,RefreshButton,useWords,WorkError,WorkHeading} from './workspace-ui';
import {useWorkInterval,useWorkSubmission,workState} from './market-data-ui';
import {DownloadJournal,DownloadJobDetails,DownloadJobActions,StandaloneDownloadJob,useDownloadJob,JobState,DownloadEtaLabel} from './data-downloads';
import {downloadPercent} from './download-progress';
import './data-workspace.css';

const exchangeName=(name:string)=>name==='binance'?'Binance':name==='bybit'?'Bybit':name;
const itemKey=(market:number,symbol:string)=>`${market}:${symbol}`;
const activeJob=(state:string|undefined)=>!!state&&['queued','running','pause_requested','paused','retry_wait','cancel_requested'].includes(state);

export function DataPage({subject}:{subject:string}) {
 const w=useWords(),{i18n}=useTranslation(),[params,setParams]=useSearchParams(),client=useQueryClient(),interval=useWorkInterval(subject);
 const defaults=useRef(closedDayRange()).current;
 const market=Number(params.get('market')??'1'),symbol=params.get('symbol')??'';
 const sources=useQuery({queryKey:['market-sources',subject],queryFn:({signal})=>readMarkets(signal),retry:false});
 const exchange=params.get('exchange')??sources.data?.items.find(m=>m.market_id===market)?.exchange_name??'binance';
 const q=params.get('q')??'',marketFilter=params.get('type')??'',history=params.get('history')??'all',stream=params.get('stream')??(params.get('selected')==='1'?'on':'all');
 const sort=params.get('sort')??'symbol',descending=params.get('direction')==='desc',offset=Math.max(0,Number(params.get('offset'))||0);
 const from=params.get('from')??defaults.from,to=params.get('to')??defaults.to,valid=validateCoverageRange(from,to);
 const requestParams=new URLSearchParams({exchange,q,history,stream,sort,descending:String(descending),offset:String(offset),limit:'50',...(marketFilter?{market_id:marketFilter}:{}),...(params.get('catalog')?{snapshot:params.get('catalog')!}:{}),...(valid?{start_at:rangeIso(from),end_at:rangeIso(to)}:{})});
 const collectionKey=requestParams.toString();
 const query=useQuery({queryKey:['exchange-catalog',subject,collectionKey],enabled:!!sources.data&&valid,retry:false,
  queryFn:({signal})=>readExchangeCatalog(requestParams,signal),refetchInterval:read=>read.state.error?false:read.state.data?.items.some(row=>activeJob(row.job?.state))?false:interval});
 const detailKey=`${market}:${symbol}:${from}:${to}`;
 const detail=useQuery({queryKey:['data-inspector',subject,detailKey],enabled:!!symbol&&valid,retry:false,
  queryFn:({signal})=>readDataInspector(market,symbol,from,to,signal),refetchInterval:read=>read.state.error||query.data?.items.some(row=>activeJob(row.job?.state))?false:interval});
 const [commandDenied,setCommandDenied]=useState(false);
 const accessLost=commandDenied||[sources.error,query.error,detail.error].some(e=>e instanceof ApiError&&[401,403].includes(e.status??0));
 const collection=useReadSnapshot(subject,collectionKey,query.isSuccess?query.data:undefined,accessLost||deniesRead(query.error));
 const inspector=useReadSnapshot(subject,detailKey,detail.isSuccess?detail.data:undefined,!symbol||accessLost||deniesRead(detail.error));
 const visible=collection.data,view=inspector.data;
 const locked=inspector.retained||!view||!!detail.error||!valid||accessLost;
 const exchanges=[...new Set(sources.data?.items.map(m=>m.exchange_name)??[])];
 const selectedSource=sources.data?.items.find(m=>m.market_id===view?.instrument.market_id);
 const [selected,setSelected]=useState<CatalogRow[]>([]);
 useEffect(()=>setSelected([]),[subject,exchange]);
 useEffect(()=>setSelected(current=>current.filter(row=>row.market_id===market)),[market]);
 const [focusDownload,setFocusDownload]=useState<string>();
 const journalOpen=params.get('journal')==='1',journalTrigger=useRef<HTMLButtonElement>(null);
 function closeJournal(){change({journal:''});journalTrigger.current?.focus();}
 function jobHref(job:WorkJob){const next=new URLSearchParams(params);if(job.market_id!==market){for(const k of ['exchange','type','offset','catalog','q','history','stream'])next.delete(k);}next.set('market',String(job.market_id));next.set('job',job.job_id);job.symbols[0]?next.set('symbol',job.symbols[0]):next.delete('symbol');return `/data?${next}`;}
 const scroll=useRef<HTMLDivElement>(null),lastCollection=useRef(collectionKey);
 useEffect(()=>{if(query.isSuccess&&lastCollection.current!==collectionKey){scroll.current?.scrollTo?.({top:0});lastCollection.current=collectionKey;}},[query.isSuccess,collectionKey]);
 function change(values:Record<string,string>,replace=true){const next=new URLSearchParams(params);for(const [k,v] of Object.entries(values)){v?next.set(k,v):next.delete(k);}setParams(next,{replace});}
 function filter(values:Record<string,string>){setSelected([]);change({...values,offset:'',catalog:''});}
 function select(row:CatalogRow){setSelected([]);change({market:String(row.market_id),symbol:row.symbol,job:row.job?.job_id??''},false);}
 function href(row:CatalogRow){const next=new URLSearchParams(params);next.set('market',String(row.market_id));next.set('symbol',row.symbol);row.job?next.set('job',row.job.job_id):next.delete('job');return `/data?${next}`;}
 function chooseExchange(name:string){setSelected([]);change({exchange:name,market:String(sources.data?.items.find(m=>m.exchange_name===name)?.market_id??1),symbol:'',job:'',type:'',offset:'',catalog:'',q:'',history:'',stream:'',selected:''},false);}
 function check(row:CatalogRow,on:boolean){if(on){if(selected.length>=50||selected.some(s=>s.market_id!==row.market_id))return;setSelected([...selected,row]);change({market:String(row.market_id),symbol:row.symbol,job:row.job?.job_id??''},false);}else setSelected(selected.filter(s=>itemKey(s.market_id,s.symbol)!==itemKey(row.market_id,row.symbol)));}
 async function refresh(){setSelected([]);if(params.get('catalog')){change({catalog:'',offset:''});}else await query.refetch();if(symbol)await detail.refetch();}
 async function changed(){await Promise.all([client.invalidateQueries({queryKey:['exchange-catalog',subject]}),client.invalidateQueries({queryKey:['data-inspector',subject]}),client.invalidateQueries({queryKey:['instrument-catalog',subject]}),client.invalidateQueries({queryKey:['data-jobs',subject]})]);}
 const [savedWork,setSavedWork]=useState<WorkJob>();
 const catalogJobId=savedWork?.kind==='catalog_refresh'?savedWork.job_id:undefined;
 const catalogCommand=useWorkSubmission(job=>{setSavedWork(job);client.setQueryData(['data-job',subject,job.job_id],job);void changed();});
 const {query:catalogJob}=useDownloadJob(subject,catalogJobId,()=>setCommandDenied(true));
 useEffect(()=>{if(deniesRead(catalogCommand.error))setCommandDenied(true);},[catalogCommand.error]);
 useEffect(()=>{if(savedWork&&!catalogCommand.pending){const range:Record<string,string>=savedWork.start_at&&savedWork.end_at&&validateCoverageRange(savedWork.start_at.slice(0,16),savedWork.end_at.slice(0,16))?{from:savedWork.start_at.slice(0,16),to:savedWork.end_at.slice(0,16)}:{};change({job:savedWork.job_id,requestkey:'',symbol:savedWork.symbols[0]??'',market:String(savedWork.market_id),...range});setSelected([]);}},[savedWork?.job_id,catalogCommand.pending]);
 const changeSort=(field:string)=>filter({sort:field,direction:sort===field&&!descending?'desc':''});
 const sortLabel=(field:string,label:string)=><button type="button" onClick={()=>changeSort(field)}>{label}{sort===field?(descending?<ArrowDown/>:<ArrowUp/>):<ArrowUpDown/>}</button>;
 return <>
  <CollectionLibrary title={w('Exchanges','Биржи')}><ReadFeedback pending={sources.isFetching} initial={!sources.data} error={sources.error}/><nav className="work-categories data-exchanges" aria-label={w('Exchanges','Биржи')}>
   {exchanges.map(name=><Link key={name} to={`/data?exchange=${name}&market=${sources.data?.items.find(m=>m.exchange_name===name)?.market_id}`} aria-current={exchange===name?'page':undefined} onClick={event=>{if(!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!event.altKey){event.preventDefault();chooseExchange(name);}}}><span className="data-exchange-mark" aria-hidden="true">{name==='binance'?'B':'By'}</span>{exchangeName(name)}<ChevronRight/></Link>)}
  </nav></CollectionLibrary>
  <WorkHeading title={exchangeName(visible?.exchange??exchange)}><span className="data-heading-subtitle">{w('Instrument catalog','Каталог инструментов')}</span><div className="work-actions"><button ref={journalTrigger} className="work-link-button" aria-expanded={journalOpen} aria-controls="data-download-journal" onClick={()=>journalOpen?closeJournal():change({journal:'1'})}>{w('Download log','Журнал загрузок')}</button><RefreshButton pending={query.isFetching} onClick={()=>void refresh()}/></div></WorkHeading>
  <section className="data-catalog panel" aria-label={w('Instrument catalog','Каталог инструментов')}>
   <div className="data-catalog-tools">
    <label className="data-search"><Search aria-hidden="true"/><span className="sr-only">{w('Search instruments','Поиск инструментов')}</span><input type="search" maxLength={64} value={q} placeholder={w('Search instruments','Поиск инструментов')} onChange={e=>filter({q:e.target.value.toUpperCase()})}/></label>
    <label className="data-select"><span className="sr-only">{w('Market','Рынок')}</span><select aria-label={w('Market','Рынок')} value={marketFilter} onChange={e=>filter({type:e.target.value})}><option value="">{w('All markets','Все рынки')}</option>{sources.data?.items.filter(m=>m.exchange_name===exchange).map(m=><option key={m.market_id} value={m.market_id}>{marketName(m.market_type,w)}</option>)}</select><ChevronDown aria-hidden="true"/></label>
    <label className="data-select"><span className="sr-only">{w('History','История')}</span><select aria-label={w('History','История')} value={history} onChange={e=>filter({history:e.target.value})}>{[['all',w('History: all','История: все')],['complete',w('Downloaded','Загружено')],['partial',w('Partial','Частично')],['empty',w('No data','Нет данных')],['active',w('Downloading / queued','Загрузка / очередь')],['failed',w('Failed','Ошибка')]].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select><ChevronDown aria-hidden="true"/></label>
    <label className="data-select"><span className="sr-only">{w('Stream','Поток')}</span><select aria-label={w('Stream','Поток')} value={stream} onChange={e=>filter({stream:e.target.value})}>{[['all',w('Stream: all','Поток: все')],['on',w('Enabled','Включён')],['off',w('Disabled','Выключен')],['pinned',w('Required by strategy','Требуется стратегии')]].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select><ChevronDown aria-hidden="true"/></label>
   </div>
   <div className="data-catalog-context"><span>{w('History','История')}: {rangeLabel(visible?.start_at??from,visible?.end_at??to,i18n.language)} · UTC · 1m</span><details className="data-range-picker"><summary>{w('Change period','Изменить период')}</summary><RangeForm key={`${from}:${to}`} from={from} to={to} onApply={(a,b)=>filter({from:a,to:b})}/></details>{(q||marketFilter||history!=='all'||stream!=='all')&&<button className="data-text-action" onClick={()=>filter({q:'',type:'',history:'',stream:'',selected:''})}>{w('Reset','Сбросить')}</button>}</div>
   <div className="data-read-status"><ReadFeedback pending={false} retained={collection.retained} initial={!visible&&valid} error={query.error}/>{!valid&&<p role="alert">{w('Choose a closed period of up to 7 days.','Выберите завершённый период не более 7 дней.')}</p>}</div>
   {!!visible?.missing_market_ids.length&&<div className="data-catalog-missing"><span>{w('Some markets have no catalog snapshot.','Для части рынков каталог ещё не загружен.')}</span>{visible.missing_market_ids.map(id=><button key={id} disabled={catalogCommand.pending||catalogCommand.unresolved||activeJob(catalogJob.data?.state)||collection.retained||accessLost} onClick={()=>void catalogCommand.submit({kind:'catalog_refresh',market_id:id})}>{w('Load catalog','Загрузить каталог')} · {marketName(sources.data?.items.find(m=>m.market_id===id)?.market_type??'',w)}</button>)}</div>}
   <WorkError error={!view?catalogCommand.error:undefined}/><WorkError error={catalogJob.error}/>{catalogJob.data&&!accessLost&&sources.data?.items.find(m=>m.market_id===catalogJob.data?.market_id)?.exchange_name===exchange&&<Link className="data-job-result" to={jobHref(catalogJob.data)}>{workState(catalogJob.data.state,w)} · {marketName(sources.data?.items.find(m=>m.market_id===catalogJob.data?.market_id)?.market_type??'',w)}<ChevronRight/></Link>}{catalogCommand.unresolved&&!view&&<button disabled={catalogCommand.pending} onClick={()=>void catalogCommand.reconcile()}>{w('Check request','Проверить задание')}</button>}
   <div className="data-catalog-scroll" ref={scroll} tabIndex={0} aria-label={w('Catalog rows','Строки каталога')}><table className="data-catalog-table"><thead><tr><th className="data-check-column"><input type="checkbox" aria-label={w('Select this page for download','Выбрать страницу для загрузки')} title={w('Select up to 50 available instruments from one market','Выбрать до 50 доступных инструментов одного рынка')} disabled={collection.retained||accessLost||!visible?.items.some(row=>row.market_id===Number(marketFilter||market)&&!activeJob(row.job?.state))} checked={!!selected.length&&!!visible?.items.filter(row=>row.market_id===Number(marketFilter||market)&&!activeJob(row.job?.state)).every(row=>selected.some(s=>itemKey(s.market_id,s.symbol)===itemKey(row.market_id,row.symbol)))} onChange={e=>{const batch=e.target.checked?visible!.items.filter(row=>row.market_id===Number(marketFilter||market)&&!activeJob(row.job?.state)).slice(0,50):[];setSelected(batch);if(batch.length)change({market:String(batch[0].market_id),symbol:batch[0].symbol,job:batch[0].job?.job_id??''},false);}}/></th>{[['symbol',w('Instrument','Инструмент')],['market',w('Market','Рынок')],['coverage',w('History / download','История / загрузка')],['stream',w('Stream','Поток')]].map(([field,label])=><th key={field} scope="col" aria-sort={sort===field?(descending?'descending':'ascending'):'none'}>{sortLabel(field,label)}</th>)}</tr></thead><tbody>
    {visible?.items.map(row=>{const key=itemKey(row.market_id,row.symbol);return <tr key={key} className={market===row.market_id&&symbol===row.symbol?'selected':''}><td><input type="checkbox" aria-label={`${w('Download','Загрузить')} ${row.symbol} · ${marketName(row.market_type,w)}`} checked={selected.some(s=>itemKey(s.market_id,s.symbol)===key)} disabled={collection.retained||accessLost||activeJob(row.job?.state)||(!selected.some(s=>itemKey(s.market_id,s.symbol)===key)&&(selected.length>=50||selected.some(s=>s.market_id!==row.market_id)))} onChange={e=>check(row,e.target.checked)}/></td><td><Link to={href(row)} aria-disabled={collection.retained||accessLost} onClick={e=>{if(collection.retained||accessLost)e.preventDefault();else setSelected([]);}} aria-current={market===row.market_id&&symbol===row.symbol?'true':undefined}>{row.symbol}</Link></td><td>{marketName(row.market_type,w)}</td><td><HistoryCell subject={subject} onDenied={()=>setCommandDenied(true)} row={row} jobHref={href(row)} onDownload={()=>{setFocusDownload(itemKey(row.market_id,row.symbol));select(row);}} disabled={collection.retained||accessLost}/></td><td><StreamStatus effective={row.effective} pinned={row.strategy_pinned}/></td></tr>;})}
   </tbody></table>{visible&&!visible.items.length&&<p className="work-empty">{w('No matching instruments','Нет подходящих инструментов')}</p>}</div>
   <footer className="data-catalog-footer"><span>{selected.length?`${w('Selected','Выбрано')}: ${selected.length} · ${w('one market, up to 50','один рынок, до 50')}`:visible?`${visible.total?visible.offset+1:0}–${Math.min(visible.offset+visible.limit,visible.total)} ${w('of','из')} ${visible.total.toLocaleString(i18n.language)}`:'—'}</span><div><button className="library-icon-action" aria-label={w('Previous page','Предыдущая страница')} disabled={!visible||visible.offset===0||collection.retained||query.isFetching} onClick={()=>change({offset:String(Math.max(0,visible!.offset-50)),catalog:visible!.snapshot})}><ChevronLeft/></button><span>{visible?Math.floor(visible.offset/50)+1:1}</span><button className="library-icon-action" aria-label={w('Next page','Следующая страница')} disabled={!visible||visible.offset+visible.limit>=visible.total||collection.retained||query.isFetching} onClick={()=>change({offset:String(visible!.offset+50),catalog:visible!.snapshot})}><ChevronRight/></button></div></footer>
   {journalOpen&&<DownloadJournal subject={subject} markets={sources.data?.items??[]} blocked={accessLost} onDenied={()=>setCommandDenied(true)} onClose={closeJournal} onSelect={()=>setSelected([])} jobHref={jobHref}/>}
  </section>
  <aside className="navigator-inspector data-inspector" aria-label={w('Instrument settings','Настройки инструмента')}>
   <ReadFeedback pending={false} retained={inspector.retained} initial={!!symbol&&!view&&valid} error={detail.error}/>
   {view?<InstrumentInspector key={itemKey(view.instrument.market_id,view.instrument.symbol)} subject={subject} latestJob={visible?.items.find(row=>row.market_id===view.instrument.market_id&&row.symbol===view.instrument.symbol)?.job} markets={sources.data?.items??[]} requestJobId={params.get('job')??(savedWork?.market_id===view.instrument.market_id&&savedWork.symbols.includes(view.instrument.symbol)?savedWork.job_id:visible?.items.find(row=>row.market_id===view.instrument.market_id&&row.symbol===view.instrument.symbol)?.job?.job_id)} focusDownload={focusDownload===itemKey(view.instrument.market_id,view.instrument.symbol)} onFocused={()=>setFocusDownload(undefined)} value={view} source={selectedSource} command={catalogCommand} saved={savedWork?.kind==='candle_ingestion'&&savedWork.market_id===view.instrument.market_id?savedWork:undefined} locked={locked} from={from} to={to} selected={collection.retained?[]:selected} onClose={()=>{setSelected([]);change({symbol:'',job:''},false);}} onChanged={changed} onDenied={()=>setCommandDenied(true)}/>:!symbol&&params.get('job')&&!accessLost?<StandaloneDownloadJob subject={subject} id={params.get('job')!} markets={sources.data?.items??[]} onDenied={()=>setCommandDenied(true)} onChanged={changed} onClose={()=>change({job:''})}/>:!symbol?<p className="work-empty">{w('Select an instrument to manage its data.','Выберите инструмент для управления данными.')}</p>:null}
  </aside>
 </>;
}

function marketName(type:string,w:ReturnType<typeof useWords>){return type==='spot'?w('Spot','Спот'):type==='futures'?w('Futures','Фьючерсы'):type;}
function rangeLabel(a:string,b:string,locale:string){const start=Date.parse(a.endsWith('Z')||/[+]\d\d:\d\d$/.test(a)?a:`${a}Z`),end=Date.parse(b.endsWith('Z')||/[+]\d\d:\d\d$/.test(b)?b:`${b}Z`);return Number.isFinite(start)&&Number.isFinite(end)?new Intl.DateTimeFormat(locale,{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'UTC'}).formatRange(start,end):'—';}
function StreamStatus({effective,pinned}:{effective:boolean;pinned:boolean}){const w=useWords();return <span className={`data-stream-state ${effective?'enabled':''}`}>{pinned?<LockKeyhole aria-hidden="true"/>:<Circle aria-hidden="true"/>}{pinned?w('Strategy','Стратегия'):effective?w('Enabled','Включён'):w('Disabled','Выключен')}</span>;}
function HistoryCell({subject,onDenied,row,jobHref,onDownload,disabled}:{subject:string;onDenied:()=>void;row:CatalogRow;jobHref:string;onDownload:()=>void;disabled:boolean}){
 const w=useWords(),summary=row.job,{query,view,eta}=useDownloadJob(subject,summary?.job_id,onDenied,undefined,true),job=view.data;
 const active=activeJob(summary?.state),percent=job?downloadPercent(job):summary?.progress_percent??0;
 if(active)return <div className="data-row-download"><Link className="data-progress data-active-progress" title={w('Download progress for this instrument','Прогресс загрузки этого инструмента')} to={jobHref} aria-disabled={disabled} onClick={e=>{if(disabled)e.preventDefault();}}>{job?<JobState {...job}/>:<span>{w('Loading…','Загрузка…')}</span>}<span className="data-progress-percent">{percent}%</span><progress max={100} value={percent} aria-label={w('Download progress','Прогресс загрузки')}/><DownloadEtaLabel eta={eta}/>{query.error&&<TriangleAlert aria-label={w('Update unavailable','Нет обновления')}/>}</Link>{job&&<DownloadJobActions compact subject={subject} job={job} locked={disabled||view.retained||!!query.error} onDenied={onDenied}/>}</div>;
 if(summary?.state==='failed')return <div className="data-row-download"><Link className="data-progress data-job-failed" to={jobHref} aria-disabled={disabled} onClick={e=>{if(disabled)e.preventDefault();}}><TriangleAlert aria-hidden="true"/><span>{w('Failed','Ошибка')}</span></Link>{job&&<DownloadJobActions compact subject={subject} job={job} locked={disabled||view.retained||!!query.error} onDenied={onDenied}/>}</div>;
 if(row.coverage_state==='empty')return <span className="data-no-history"><Circle aria-hidden="true"/><span>{w('No data','Нет данных')}</span><button type="button" className="library-icon-action data-download-icon" aria-label={`${w('Download','Загрузить')} ${row.symbol} · ${marketName(row.market_type,w)}`} title={w('Download','Загрузить')} disabled={disabled} onClick={onDownload}><Download aria-hidden="true"/></button></span>;
 return <span className={`data-progress ${row.coverage_state==='complete'?'complete':''}`} title={`${row.actual_candles} / ${row.expected_candles} · ${w('closed candles in this period','завершённых свечей за период')}`}>{row.coverage_state==='complete'?<CheckCircle2 aria-hidden="true"/>:<Circle aria-hidden="true"/>}<span>{row.coverage_percent}%</span><progress max={100} value={row.coverage_percent} aria-label={w('Candle coverage','Покрытие свечей')}/></span>;
}

function RangeForm({from,to,onApply}:{from:string;to:string;onApply:(a:string,b:string)=>void}){
 const w=useWords(),[a,setA]=useState(from),[b,setB]=useState(to),[error,setError]=useState(false);
 return <form onSubmit={e=>{e.preventDefault();if(!validateCoverageRange(a,b)){setError(true);e.currentTarget.querySelector('input')?.focus();return;}onApply(a,b);e.currentTarget.closest('details')?.removeAttribute('open');}}><div className="data-range-fields"><label>{w('From · UTC','С · UTC')}<input type="datetime-local" required value={a} onInput={e=>setA(e.currentTarget.value)} onChange={e=>setA(e.target.value)}/></label><label>{w('To · UTC','По · UTC')}<input type="datetime-local" required value={b} onInput={e=>setB(e.currentTarget.value)} onChange={e=>setB(e.target.value)}/></label></div>{error&&<p role="alert">{w('Choose 1–10,080 closed minutes.','Выберите 1–10 080 завершённых минут.')}</p>}<button className="primary" type="submit">{w('Apply','Применить')}</button></form>;
}

function InstrumentInspector({subject,latestJob,markets,requestJobId,focusDownload,onFocused,value,source,command,saved,locked,from,to,selected,onClose,onChanged,onDenied}:{subject:string;latestJob:CatalogRow['job']|undefined;markets:Market[];requestJobId:string|undefined;focusDownload:boolean;onFocused:()=>void;value:DataInspector;source:Market|undefined;command:ReturnType<typeof useWorkSubmission>;saved:WorkJob|undefined;locked:boolean;from:string;to:string;selected:CatalogRow[];onClose:()=>void;onChanged:()=>Promise<void>;onDenied:()=>void}){
 const w=useWords(),{i18n}=useTranslation(),item=value.instrument,coverage=value.coverage,client=useQueryClient();
 const [pending,setPending]=useState(false),[error,setError]=useState<unknown>(),[unknown,setUnknown]=useState(false),busy=useRef(false);
 const [draft,setDraft]=useState<{key:string;from:string;to:string}>(),[validation,setValidation]=useState(false);
 const batchMatches=selected.every(row=>row.market_id===item.market_id);
 const names=selected.length?selected.map(r=>r.symbol):[item.symbol];
 const [manual,setManual]=useState(false),batch=names.length>1;
 const monthEnd=new Date();monthEnd.setUTCDate(1);monthEnd.setUTCHours(0,0,0,0);const monthStart=new Date(monthEnd);monthStart.setUTCMonth(monthStart.getUTCMonth()-1);
 const rangeKey=`${item.market_id}:${[...names].sort().join(',')}`;
 const bounds=useQueries({queries:names.map(name=>({queryKey:['history-bounds',subject,item.market_id,name],queryFn:({signal}:{signal:AbortSignal})=>readHistoryBounds(item.market_id,name,signal),enabled:!locked&&!manual&&!batch,retry:false,staleTime:60_000,refetchInterval:(read:{state:{error:unknown;data?:{state:string}}})=>read.state.error?false:read.state.data&&['queued','running'].includes(read.state.data.state)?2000:false}))});
 const allReady=bounds.every(read=>read.data?.state==='ready'&&read.data.first_open_at);
 const resolving=!manual&&!batch&&bounds.some(read=>!read.error&&(!read.data||['queued','running'].includes(read.data.state)));
 const boundsError=bounds.find(read=>read.error)?.error,boundsDenied=bounds.some(read=>deniesRead(read.error));
 const defaultFrom=batch?monthStart.toISOString().slice(0,16):allReady?bounds.map(read=>read.data!.first_open_at!).sort()[0].slice(0,16):'';
 const defaultTo=batch?monthEnd.toISOString().slice(0,16):bounds.map(read=>read.data?.end_at??'').filter(Boolean).sort()[0]?.slice(0,16)??'';
 const a=draft?.key===rangeKey?draft.from:defaultFrom,b=draft?.key===rangeKey?draft.to:defaultTo;
 const setA=(from:string)=>setDraft({key:rangeKey,from,to:b}),setB=(to:string)=>setDraft({key:rangeKey,from:a,to});
 const downloadLocked=locked||activeJob(latestJob?.state)||(resolving&&!manual)||command.pending||command.unresolved;
 useEffect(()=>{if(focusDownload&&!downloadLocked){document.getElementById('data-download-from')?.focus();onFocused();}},[focusDownload,downloadLocked]);
 useEffect(()=>{if(boundsDenied)onDenied();},[boundsDenied]);
 const {query:job,view:jobView,eta}=useDownloadJob(subject,requestJobId,onDenied);
 const jobMatches=jobView.data?.market_id===item.market_id&&jobView.data.symbols.includes(item.symbol);
 useEffect(()=>{if(deniesRead(command.error))onDenied();},[command.error,job.error]);
 const dirty=!!draft&&draft.key===rangeKey&&(a!==defaultFrom||b!==defaultTo);
 async function toggle(){if(locked||item.strategy_pinned||busy.current||unknown)return;busy.current=true;setPending(true);setError(undefined);try{await selectInstrument(item,!item.effective);await onChanged();}catch(e){setError(e);setUnknown(e instanceof ApiError&&e.outcome==='unknown');if(deniesRead(e))onDenied();}finally{busy.current=false;setPending(false);}}
 async function reconcile(){setPending(true);try{await onChanged();const result=await readDataInspector(item.market_id,item.symbol,from,to);client.setQueryData(['data-inspector',subject,`${item.market_id}:${item.symbol}:${from}:${to}`],result);setUnknown(false);setError(undefined);}catch(e){setError(e);if(deniesRead(e))onDenied();}finally{setPending(false);}}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setValidation(true);if(!validateWorkRange(a,b,names)){e.currentTarget.querySelector('input')?.focus();return;}if(downloadLocked||!batchMatches||(jobMatches&&activeJob(jobView.data?.state))||!!(requestJobId&&(job.isPending||job.error||jobView.retained)))return;void command.submit({kind:'candle_ingestion',market_id:item.market_id,symbols:names,timeframe:'1m',start_at:rangeIso(a),end_at:rangeIso(b)});}
 return <><DirtyGuard dirty={(dirty&&!(saved?.start_at?.slice(0,16)===a&&saved?.end_at?.slice(0,16)===b))||command.pending}/><header className="data-inspector-heading"><div><h2>{item.symbol}</h2><p>{exchangeName(source?.exchange_name??'')} · {marketName(source?.market_type??'',w)} · 1m</p></div><button className="library-icon-action" aria-label={w('Close instrument','Закрыть инструмент')} onClick={onClose}><X/></button></header>
  {latestJob&&activeJob(latestJob.state)&&latestJob.job_id!==requestJobId&&<Link className="data-job-result" to={`/data?${new URLSearchParams({market:String(item.market_id),symbol:item.symbol,job:latestJob.job_id})}`}>{w('Open current download','Открыть текущую загрузку')}<ChevronRight aria-hidden="true"/></Link>}
  {requestJobId&&<><ReadFeedback pending={false} retained={jobView.retained} initial={!jobView.data} error={job.error}/>{job.error&&<button disabled={job.isFetching} onClick={()=>void job.refetch()}>{w('Refresh request','Обновить задание')}</button>}{jobMatches&&jobView.data&&<DownloadJobDetails key={jobView.data.job_id} subject={subject} job={jobView.data} eta={eta} markets={markets} locked={locked||jobView.retained||!!job.error} onDenied={onDenied} onChanged={onChanged}/>}</>}
  <section className="data-inspector-section"><div className="data-stream-control"><h3>{w('Streaming','Потоковый сбор')}</h3><button type="button" role="switch" aria-label={w('Streaming','Потоковый сбор')} aria-checked={item.effective} aria-describedby="data-stream-help" className="data-stream-switch" disabled={locked||pending||unknown||item.strategy_pinned} onClick={()=>void toggle()}><span/></button>{item.strategy_pinned&&<LockKeyhole className="data-lock" aria-hidden="true"/>}</div>
  <p id="data-stream-help">{item.strategy_pinned?w('Cannot disable: this instrument is required by active strategies.','Нельзя отключить: инструмент нужен активным стратегиям.'):w('Collect new closed 1m candles. Existing history is preserved when disabled.','Собирать новые завершённые свечи 1m. При отключении история сохраняется.')}</p>
  {!!item.strategies.length&&<ul className="data-strategy-pins">{item.strategies.map(s=><li key={s.strategy_id}><Link to={`/strategies/${s.strategy_id}`}>{s.name}</Link><span>{workState(s.state,w)}</span></li>)}</ul>}
  <dl className="data-last-candle"><dt>{w('Last candle · UTC','Последняя свеча · UTC')}</dt><dd>{formatTime(item.last_candle_at,i18n.language)}</dd></dl>
  {item.effective&&<p className="data-stream-observation">{!item.last_candle_at?w('No candles observed yet.','Свечи ещё не получены.'):Date.parse(item.observed_at)-Date.parse(item.last_candle_at)>180000?w('Latest stored candle is delayed. Check the collector.','Последняя сохранённая свеча запаздывает. Проверьте сборщик.'):w('Recent candles are present.','Есть свежие свечи.')}</p>}
  <WorkError error={error}/>{unknown&&<button disabled={pending} onClick={()=>void reconcile()}>{w('Check saved state','Проверить сохранённое состояние')}</button>}</section>
  <section className="data-inspector-section"><h3>{w('Stored history','Сохранённая история')}</h3><div className={`data-inspector-coverage ${coverage.state==='complete'?'complete':''}`}>{coverage.state==='complete'?<CheckCircle2 aria-hidden="true"/>:<Circle aria-hidden="true"/>}<strong>{coverage.coverage_percent}%</strong><span>{coverage.actual_candles.toLocaleString(i18n.language)} / {coverage.expected_candles.toLocaleString(i18n.language)}</span></div><progress max={100} value={coverage.coverage_percent} aria-label={w('Selected period coverage','Покрытие выбранного периода')}/><p>{rangeLabel(coverage.start_at,coverage.end_at,i18n.language)} · UTC</p>
   <form onSubmit={submit}><h3>{selected.length>1?`${w('Download','Загрузить')}: ${selected.length} ${w('instruments','инструмента')}`:w('Download period','Загрузить период')}</h3>{selected.length>1&&<p>{names.join(', ')}</p>}{resolving&&<p role="status">{w('Finding the first available candle…','Определяем первую доступную свечу…')}</p>}{resolving&&!manual&&<button type="button" disabled={locked} onClick={()=>setManual(true)}>{w('Enter period manually','Указать период вручную')}</button>}{!batch&&!resolving&&!allReady&&<p>{w('History start is unavailable. Retry or enter a period manually.','Не удалось определить начало истории. Повторите проверку или укажите период вручную.')}</p>}<WorkError error={boundsError}/>{!batch&&!resolving&&!allReady&&<button type="button" disabled={locked} onClick={()=>void Promise.all(bounds.map(read=>read.refetch()))}>{w('Find full history','Определить всю историю')}</button>}<fieldset className="data-range-fields" disabled={downloadLocked}><Field name="data-download-from" label={w('From · UTC','С · UTC')}><input id="data-download-from" type="datetime-local" required value={a} aria-invalid={validation&&!validateWorkRange(a,b,names)} onInput={e=>setA(e.currentTarget.value)} onChange={e=>setA(e.target.value)}/></Field><Field name="data-download-to" label={w('To · UTC','По · UTC')}><input id="data-download-to" type="datetime-local" required value={b} onInput={e=>setB(e.currentTarget.value)} onChange={e=>setB(e.target.value)}/></Field></fieldset>
   {validation&&!validateWorkRange(a,b,names)&&<p className="notice error" role="alert">{w('Choose up to 50 instruments and a valid period of closed candles.','Выберите до 50 инструментов и корректный период завершённых свечей.')}</p>}
   <button className="primary data-download-button" type="submit" disabled={downloadLocked||!batchMatches||!validateWorkRange(a,b,names)||(jobMatches&&activeJob(jobView.data?.state))||!!(requestJobId&&(job.isPending||job.error||jobView.retained))}><Download aria-hidden="true"/>{command.pending?w('Requesting…','Отправка…'):w('Download period','Загрузить период')}</button><p>{batch?w('Each instrument gets a separate queued download. Defaults to the last complete month.','Каждый инструмент получит отдельное задание в очереди. По умолчанию — последний полный месяц.'):w('Defaults to all available history. Existing candles are preserved.','По умолчанию — вся доступная история. Существующие свечи сохранятся.')}</p>
  </form><WorkError error={command.error}/>{command.unresolved&&<button disabled={command.pending} onClick={()=>void command.reconcile()}>{w('Check request','Проверить задание')}</button>}
  </section>
  <details className="data-instrument-details"><summary>{w('Instrument details','Параметры инструмента')}</summary><dl><dt>{w('Assets','Активы')}</dt><dd>{item.base_asset} / {item.quote_asset}</dd><dt>{w('Price step','Шаг цены')}</dt><dd>{item.price_step??'—'}</dd><dt>{w('Quantity step','Шаг количества')}</dt><dd>{item.qty_step??'—'}</dd><dt>{w('Minimum order','Минимальный ордер')}</dt><dd>{item.min_notional??'—'} {item.quote_asset}</dd><dt>{w('Catalog updated · UTC','Каталог обновлён · UTC')}</dt><dd>{formatTime(item.refreshed_at,i18n.language)}</dd></dl></details>
 </>;
}
