import {z} from 'zod';
import {requestJson,ApiError} from './api';

export const instrumentSchema=z.object({market_id:z.number(),symbol:z.string(),base_asset:z.string().nullable(),quote_asset:z.string().nullable(),price_step:z.number().nullable(),qty_step:z.number().nullable(),min_notional:z.number().nullable(),selected:z.boolean(),strategy_pinned:z.boolean(),effective:z.boolean()});
export const catalogSchema=z.object({snapshot_id:z.string().nullable(),refreshed_at:z.string().nullable(),catalog_state:z.string(),total:z.number(),items:z.array(instrumentSchema),next_cursor:z.string().nullable()});
export const coverageSchema=z.object({market_id:z.number(),symbol:z.string(),timeframe:z.string(),start_at:z.string(),end_at:z.string(),state:z.string(),expected_candles:z.number(),actual_candles:z.number(),coverage_percent:z.number(),observed_at:z.string(),gap_count:z.number(),gaps_truncated:z.boolean(),gaps:z.array(z.object({start_at:z.string(),end_at:z.string(),missing_candles:z.number()}))});
export const workJobSchema=z.object({job_id:z.string(),kind:z.enum(['catalog_refresh','candle_ingestion']),market_id:z.number(),symbols:z.array(z.string()),timeframe:z.string(),start_at:z.string().nullable(),end_at:z.string().nullable(),state:z.string(),attempt:z.number(),completed_units:z.number(),total_units:z.number(),rows_read:z.number(),rows_written:z.number(),error_code:z.string().nullable(),created_at:z.string(),updated_at:z.string(),started_at:z.string().nullable(),finished_at:z.string().nullable(),can_cancel:z.boolean(),can_retry:z.boolean(),can_pause:z.boolean().optional(),can_resume:z.boolean().optional(),control_version:z.number().optional(),progress_epoch:z.number().optional(),retry_count:z.number().optional(),next_retry_at:z.string().nullable().optional(),error_phase:z.string().nullable().optional(),queue_waiting:z.boolean().optional(),storage_retry_at:z.string().nullable().optional(),attempts:z.array(z.object({attempt:z.number(),state:z.string(),error_code:z.string().nullable(),finished_at:z.string(),rows_read:z.number().nullable().optional(),rows_written:z.number().nullable().optional()}))});
export const workHistorySchema=z.object({items:z.array(workJobSchema),next_cursor:z.object({before:z.string(),before_id:z.string()}).nullable()});
export type Instrument=z.infer<typeof instrumentSchema>;
export type WorkJob=z.infer<typeof workJobSchema>;
export type Coverage=z.infer<typeof coverageSchema>;
export type WorkCommand={kind:'catalog_refresh'|'candle_ingestion';market_id:number;symbols?:string[];start_at?:string;end_at?:string;timeframe?:'1m'};
export const marketRead=async<T>(path:string,schema:z.ZodType<T>,signal?:AbortSignal)=>(await requestJson(`/api/market-data/${path}`,schema,{signal})).data;
export const readCatalog=(params:URLSearchParams,signal?:AbortSignal)=>marketRead(`workspace/catalog?${params}`,catalogSchema,signal);
export async function readInstrument(market:number,symbol:string,signal?:AbortSignal){const page=await readCatalog(new URLSearchParams({market_id:String(market),q:symbol,limit:'1'}),signal);const item=page.items.find(r=>r.symbol===symbol);if(!item)throw new ApiError('not-found',404,'failed');return {...item,snapshot_id:page.snapshot_id,refreshed_at:page.refreshed_at,catalog_state:page.catalog_state};}
export const submitWork=(body:WorkCommand,idempotency_key:string)=>body.kind==='candle_ingestion'&&(body.symbols?.length??0)>1
 ?requestJson('/api/market-data/work-batches',z.object({items:z.array(workJobSchema).min(1),batch_key:z.string()}),{method:'POST',body:{...body,idempotency_key}}).then(r=>r.data.items[0])
 :requestJson('/api/market-data/work-requests',workJobSchema,{method:'POST',body:{...body,idempotency_key}}).then(r=>r.data);
export const workEventsSchema=z.object({items:z.array(z.object({event_id:z.number(),event_type:z.string(),occurred_at:z.string(),state:z.string(),attempt:z.number(),completed_units:z.number(),total_units:z.number(),rows_written:z.number(),error_code:z.string().nullable(),error_phase:z.string().nullable(),next_retry_at:z.string().nullable()})),next_cursor:z.number().nullable(),retention_days:z.number(),max_events:z.number()});
export const workAction=(id:string,action:'cancel'|'retry'|'pause'|'resume',attempt:number,control_version=0)=>requestJson(`/api/market-data/work-requests/${encodeURIComponent(id)}/${action}`,workJobSchema,{method:'POST',body:action==='retry'?{attempt}:action==='pause'||action==='resume'?{control_version}:undefined}).then(r=>r.data);
export const readJob=(id:string,signal?:AbortSignal)=>marketRead(`work-requests/${encodeURIComponent(id)}`,workJobSchema,signal);
export const lookupWork=(key:string)=>marketRead(`work-requests/lookup?${new URLSearchParams({key})}`,workJobSchema);
export async function selectInstrument(item:Instrument,selected:boolean){return requestJson(`/api/market-data/selections/${item.market_id}/${encodeURIComponent(item.symbol)}`,z.object({market_id:z.number(),symbol:z.string(),effective:z.boolean(),strategy_pinned:z.boolean()}),{method:selected?'PUT':'DELETE'});}
export const dateInput=(date:Date)=>date.toISOString().slice(0,16);
export function closedDayRange(){const end=new Date();end.setUTCSeconds(0,0);return {from:dateInput(new Date(end.getTime()-86400000)),to:dateInput(end)};}
export function rangeIso(value:string){return new Date(`${value}Z`).toISOString();}
export function validateWorkRange(from:string,to:string,symbols:string[]){const a=Date.parse(`${from}Z`),b=Date.parse(`${to}Z`),minutes=(b-a)/60000,total=minutes*symbols.length;return Number.isFinite(total)&&Number.isInteger(minutes)&&minutes>0&&total<=2147483647&&a>=Date.parse('2017-01-01Z')&&b<=Math.floor(Date.now()/60000)*60000&&symbols.length>0&&symbols.length<=50&&new Set(symbols).size===symbols.length&&symbols.every(s=>/^[A-Z0-9][A-Z0-9._-]{1,63}$/.test(s));}

export function validateCoverageRange(from:string,to:string){return validateWorkRange(from,to,['BTCUSDT'])&&(Date.parse(`${to}Z`)-Date.parse(`${from}Z`))/60000<=10080;}
