import {useEffect,useState} from 'react';
import {Link,useLocation,useSearchParams} from 'react-router';
import {useQuery} from '@tanstack/react-query';
import {useTranslation} from 'react-i18next';
import {z} from 'zod';
import {ApiError,requestJson} from './api';
import {useReadSnapshot} from './read-snapshot';
import {useWorkInterval} from './market-data-ui';
import {NavigatorTable} from './navigator-table';
import {CollectionLibrary,deniesRead,formatTime,ReadFeedback,RefreshButton,useWords,WorkHeading} from './workspace-ui';

const serviceSchema=z.object({service_id:z.string(),group:z.string(),capability:z.string(),state:z.enum(['healthy','degraded','unavailable','unknown','stale']),observed_at:z.string(),detail_code:z.string(),signal_source:z.string(),runbook_path:z.string().nullable(),required:z.boolean()});
const inventorySchema=z.object({generated_at:z.string(),groups:z.array(z.string()),services:z.array(serviceSchema),events:z.array(serviceSchema),history_state:z.string(),history_scope:z.string(),commands:z.array(z.string())});
const detailSchema=z.object({service:serviceSchema,generated_at:z.string(),events:z.array(serviceSchema),history_state:z.string(),history_scope:z.string(),metrics:z.array(z.unknown()),dependencies:z.array(z.unknown()),commands:z.array(z.string())});
type Service=z.infer<typeof serviceSchema>;
const groups=['core','data','compute','trading','security','extensions'];
function groupName(key:string,w:ReturnType<typeof useWords>){return ({core:w('Platform core','Ядро платформы'),data:w('Data','Данные'),compute:w('Compute','Вычисления'),trading:w('Trading','Торговля'),security:w('Security','Безопасность'),extensions:w('Extensions','Расширения')})[key]??key;}
function serviceName(id:string){return ({api:'API',web:'Web',postgresql:'PostgreSQL',clickhouse:'ClickHouse',redis:'Redis',openbao:'OpenBao'})[id]??id.replaceAll('-',' ');}
function stateName(key:string,w:ReturnType<typeof useWords>){return ({healthy:w('Healthy','Работает'),degraded:w('Degraded','Деградация'),unavailable:w('Unavailable','Недоступен'),unknown:w('Unknown','Неизвестно'),stale:w('Stale observation','Устаревшее наблюдение')})[key]??key;}
function signal(code:string,w:ReturnType<typeof useWords>){return ({'probe.domain_ready':w('Application readiness confirmed','Готовность приложения подтверждена'),'probe.reachable_no_readiness':w('Port reachable; readiness is not confirmed','Порт доступен; готовность не подтверждена'),'probe.connection_refused':w('Connection refused','Соединение отклонено'),'probe.unreachable':w('Service could not be reached','Сервис не отвечает'),'probe.timeout':w('Probe timed out','Истекло время проверки'),'probe.response_invalid':w('Invalid health response','Некорректный ответ проверки'),'probe.snapshot_stale':w('Observer has stopped updating','Наблюдатель перестал обновлять данные'),'probe.domain_degraded':w('Application reports degraded health','Приложение сообщает о деградации'),'probe.domain_unknown':w('Application readiness is unknown','Готовность приложения неизвестна')})[code]??w('Readiness is not confirmed','Готовность не подтверждена');}
function actualState(service:Service,now:number){return now-Date.parse(service.observed_at)>30000?'stale':service.state;}

export function MonitoringPage({subject}:{subject:string}){
 const w=useWords(),{i18n}=useTranslation(),location=useLocation(),[params,setParams]=useSearchParams(),interval=useWorkInterval(subject),id=location.pathname.split('/')[2]??'',q=params.get('q')??'',filter=params.get('group')??'';
 const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),10000);return()=>clearInterval(timer);},[]);
 const query=useQuery({queryKey:['monitoring',subject],retry:false,queryFn:({signal})=>requestJson('/api/ui/monitoring',inventorySchema,{signal}).then(r=>r.data),refetchInterval:q=>q.state.error?false:interval});
 const selected=useQuery({queryKey:['monitoring-service',subject,id],enabled:!!id,retry:false,queryFn:({signal})=>requestJson(`/api/ui/monitoring/${encodeURIComponent(id)}`,detailSchema,{signal}).then(r=>r.data),refetchInterval:q=>q.state.error?false:interval});
 const accessError=[query.error,selected.error].find(e=>e instanceof ApiError&&[401,403].includes(e.status??0));
 const inventory=useReadSnapshot(subject,'services',query.isSuccess?query.data:undefined,!!accessError||deniesRead(query.error));
 const view=useReadSnapshot(subject,id,selected.isSuccess?selected.data:undefined,!id||!!accessError||deniesRead(selected.error)||deniesRead(query.error));
 const detail=view.data;
 function change(name:string,value:string){const next=new URLSearchParams(params);value?next.set(name,value):next.delete(name);setParams(next,{replace:true});}
 function refresh(){void query.refetch();if(id)void selected.refetch();}
 return <><CollectionLibrary title={w('Services','Сервисы')} actions={<RefreshButton pending={query.isFetching||selected.isFetching} onClick={refresh}/>}
  filters={<><label>{w('Search','Поиск')}<input value={q} maxLength={80} onChange={e=>change('q',e.target.value)}/></label><label>{w('Group','Группа')}<select value={filter} onChange={e=>change('group',e.target.value)}><option value="">{w('All','Все')}</option>{groups.map(g=><option key={g} value={g}>{groupName(g,w)}</option>)}</select></label></>}
  onReset={()=>setParams(new URLSearchParams(),{replace:true})}>
   <ReadFeedback pending={query.isFetching} initial={!inventory.data} error={accessError??query.error}/>{inventory.data&&groups.filter(g=>!filter||g===filter).map(g=>{const rows=inventory.data!.services.filter(s=>s.group===g&&serviceName(s.service_id).toLowerCase().includes(q.toLowerCase()));return <div key={g}><h3 className="work-list-group">{groupName(g,w)}</h3>{rows.map(s=><Link key={s.service_id} className="work-object-row" aria-current={id===s.service_id?'true':undefined} to={`/monitoring/${encodeURIComponent(s.service_id)}?${params}`}><strong>{serviceName(s.service_id)}</strong><span>{stateName(actualState(s,now),w)}</span></Link>)}{!rows.length&&<p className="work-service-empty">{q?w('No matches','Нет совпадений'):w('No configured services','Нет настроенных сервисов')}</p>}</div>;})}
 </CollectionLibrary><WorkHeading title={detail?serviceName(detail.service.service_id):w('Monitoring','Мониторинг')}><RefreshButton pending={query.isFetching||selected.isFetching} onClick={refresh}/></WorkHeading><div className="work-content">
  <ReadFeedback pending={selected.isFetching} retained={view.retained} initial={!!id&&!detail} error={selected.error}/>
  {detail?<><section className="panel"><dl className="work-kv"><dt>{w('State','Состояние')}</dt><dd>{stateName(actualState(detail.service,now),w)}</dd><dt>{w('Group','Группа')}</dt><dd>{groupName(detail.service.group,w)}</dd><dt>{w('Signal','Сигнал')}</dt><dd>{signal(detail.service.detail_code,w)}</dd><dt>{w('Observed · UTC','Наблюдение · UTC')}</dt><dd>{formatTime(detail.service.observed_at,i18n.language)} · {Math.max(0,Math.floor((now-Date.parse(detail.service.observed_at))/1000))} {w('seconds ago','секунд назад')}</dd><dt>{w('Source','Источник')}</dt><dd>Operational health</dd></dl><div className="work-actions work-section-actions">{detail.service.runbook_path&&<a className="work-link-button" href={detail.service.runbook_path}>{w('Open runbook','Открыть инструкцию')}</a>}{detail.service.group==='data'&&<Link className="work-link-button" to="/data?journal=1">{w('Market Data requests','Задания рыночных данных')}</Link>}</div></section>{detail.service.group==='data'&&<DataBacklog subject={subject}/>}<NavigatorTable tabs={[{id:'service-events',label:w('Recent events','Последние события'),content:<><div className="work-history-status">{detail.history_state==='available'?w('Observed state changes since this observer started','Изменения состояния с запуска наблюдателя'):w('Event history is unavailable','История событий недоступна')}</div><table><thead><tr><th>{w('Observed · UTC','Наблюдение · UTC')}</th><th>{w('State','Состояние')}</th><th>{w('Signal','Сигнал')}</th></tr></thead><tbody>{detail.events.map((e,n)=><tr key={`${e.observed_at}:${n}`}><td>{formatTime(e.observed_at,i18n.language)}</td><td>{stateName(e.state,w)}</td><td>{signal(e.detail_code,w)}</td></tr>)}</tbody></table></>}]}/></>:!id&&inventory.data?<NavigatorTable tabs={[{id:'services',label:w('Services','Сервисы'),content:<table><thead><tr><th>{w('Service','Сервис')}</th><th>{w('State','Состояние')}</th><th>{w('Observed · UTC','Наблюдение · UTC')}</th></tr></thead><tbody>{inventory.data.services.map(s=><tr key={s.service_id}><td><Link to={`/monitoring/${encodeURIComponent(s.service_id)}`}>{serviceName(s.service_id)}</Link></td><td>{stateName(actualState(s,now),w)}</td><td>{formatTime(s.observed_at,i18n.language)}</td></tr>)}</tbody></table>}]}/>:null}
 </div></>;
}

const backlogSchema=z.object({queued:z.number(),running:z.number(),cancel_requested:z.number(),oldest_queued_at:z.string().nullable(),observed_at:z.string()});
function DataBacklog({subject}:{subject:string}){
 const w=useWords(),{i18n}=useTranslation(),interval=useWorkInterval(subject);
 const query=useQuery({queryKey:['data-backlog',subject],queryFn:({signal})=>requestJson('/api/market-data/workspace/backlog',backlogSchema,{signal}).then(r=>r.data),retry:false,refetchInterval:q=>q.state.error?false:interval});
 const view=useReadSnapshot(subject,'backlog',query.isSuccess?query.data:undefined,deniesRead(query.error));
 return <section className="panel"><h2>{w('Market Data requests · current organization','Задания рыночных данных · текущая организация')}</h2><ReadFeedback pending={query.isFetching} retained={view.retained} initial={!view.data} error={query.error}/>{view.data&&<dl className="work-kv"><dt>{w('Queued / running / cancelling','В очереди / выполняются / отменяются')}</dt><dd>{view.data.queued} / {view.data.running} / {view.data.cancel_requested}</dd><dt>{w('Oldest queued · UTC','Старейшее в очереди · UTC')}</dt><dd>{formatTime(view.data.oldest_queued_at,i18n.language)}</dd><dt>{w('Observed · UTC','Наблюдение · UTC')}</dt><dd>{formatTime(view.data.observed_at,i18n.language)}</dd></dl>}<div className="work-actions work-section-actions"><Link className="work-link-button" to="/data?journal=1&jobstate=queued">{w('Open queued requests','Открыть очередь')}</Link><RefreshButton pending={query.isFetching} onClick={()=>void query.refetch()}/></div></section>;
}
