from __future__ import annotations

from trading.contexts.identity.application.ports.current_user import (
    CurrentUser,
    CurrentUserPrincipal,
    CurrentUserUnauthorizedError,
)
from trading.contexts.identity.application.ports.jwt_codec import JwtCodec, JwtDecodeError
from trading.contexts.identity.application.ports.user_repository import UserRepository


class JwtCookieCurrentUser(CurrentUser):
    """
    JwtCookieCurrentUser — реализация CurrentUser порта через JWT cookie и user repository.

    Docs:
      - docs/architecture/identity/identity-telegram-login-user-model-v1.md
    Related:
      - src/trading/contexts/identity/application/ports/current_user.py
      - src/trading/contexts/identity/application/ports/jwt_codec.py
      - src/trading/contexts/identity/adapters/inbound/api/deps/current_user.py
    """

    def __init__(
        self,
        *,
        jwt_codec: JwtCodec,
        user_repository: UserRepository,
    ) -> None:
        """
        Initialize current-user resolver dependencies.

        Args:
            jwt_codec: Verified JWT decoder.
            user_repository: User repository for active-user lookup.
        Returns:
            None.
        Assumptions:
            Dependencies are initialized and non-null.
        Raises:
            ValueError: If required dependency is missing.
        Side Effects:
            None.
        """
        if jwt_codec is None:  # type: ignore[truthy-bool]
            raise ValueError("JwtCookieCurrentUser requires jwt_codec")
        if user_repository is None:  # type: ignore[truthy-bool]
            raise ValueError("JwtCookieCurrentUser requires user_repository")
        self._jwt_codec = jwt_codec
        self._user_repository = user_repository

    def require(self, *, token: str | None) -> CurrentUserPrincipal:
        """
        Resolve active current user from JWT token.

        Args:
            token: Cookie token value.
        Returns:
            CurrentUserPrincipal: Stable user identity context.
        Assumptions:
            Token was generated by identity login flow.
        Raises:
            CurrentUserUnauthorizedError: If token missing/invalid or user not active.
        Side Effects:
            Reads user snapshot from repository.
        """
        token_value = "" if token is None else token.strip()
        if not token_value:
            raise CurrentUserUnauthorizedError(
                code="missing_jwt_cookie",
                message="JWT cookie is required",
            )

        try:
            claims = self._jwt_codec.decode(token=token_value)
        except JwtDecodeError as error:
            raise CurrentUserUnauthorizedError(code=error.code, message=error.message) from error

        user = self._user_repository.find_by_user_id(user_id=claims.user_id)
        if user is None:
            raise CurrentUserUnauthorizedError(
                code="unknown_user",
                message="User from JWT token does not exist",
            )
        if user.is_deleted:
            raise CurrentUserUnauthorizedError(
                code="deleted_user",
                message="User account is deleted",
            )

        return CurrentUserPrincipal(
            user_id=user.user_id,
            paid_level=user.paid_level,
        )
